//autogenerated on 7/27/2016 8:36:07 PM
namespace CSGL.GL4 {
    public enum AttribMask : uint {
        ColorBufferBit = 0x00004000,
        DepthBufferBit = 0x00000100,
        StencilBufferBit = 0x00000400,
    }

    public enum AlphaFunction : uint {
        Always = 0x0207,
        Equal = 0x0202,
        Gequal = 0x0206,
        Greater = 0x0204,
        Lequal = 0x0203,
        Less = 0x0201,
        Never = 0x0200,
        Notequal = 0x0205,
    }

    public enum BlendingFactor : uint {
        DstAlpha = 0x0304,
        One = 1,
        OneMinusDstAlpha = 0x0305,
        OneMinusSrcAlpha = 0x0303,
        OneMinusSrcColor = 0x0301,
        SrcAlpha = 0x0302,
        SrcColor = 0x0300,
        Zero = 0,
    }

    public enum Boolean : uint {
        False = 0,
        True = 1,
    }

    public enum ClearBufferMask : uint {
        ColorBufferBit = 0x00004000,
        DepthBufferBit = 0x00000100,
        StencilBufferBit = 0x00000400,
    }

    public enum ClipPlaneName : uint {
        ClipDistance0 = 0x3000,
        ClipDistance1 = 0x3001,
        ClipDistance2 = 0x3002,
        ClipDistance3 = 0x3003,
        ClipDistance4 = 0x3004,
        ClipDistance5 = 0x3005,
        ClipDistance6 = 0x3006,
        ClipDistance7 = 0x3007,
    }

    public enum Face : uint {
        Back = 0x0405,
        Front = 0x0404,
        FrontAndBack = 0x0408,
    }

    public enum ColorPointerType : uint {
        Byte = 0x1400,
        Double = 0x140A,
        Float = 0x1406,
        Int = 0x1404,
        Short = 0x1402,
        UnsignedByte = 0x1401,
        UnsignedInt = 0x1405,
        UnsignedShort = 0x1403,
    }

    public enum ContextFlagMask : uint {
        ContextFlagDebugBit = 0x00000002,
        ContextFlagForwardCompatibleBit = 0x00000001,
    }

    public enum ContextProfileMask : uint {
        ContextCompatibilityProfileBit = 0x00000002,
        ContextCoreProfileBit = 0x00000001,
    }

    public enum DepthFunction : uint {
        Always = 0x0207,
        Equal = 0x0202,
        Gequal = 0x0206,
        Greater = 0x0204,
        Lequal = 0x0203,
        Less = 0x0201,
        Never = 0x0200,
        Notequal = 0x0205,
    }

    public enum DrawBufferMode : uint {
        Back = 0x0405,
        BackLeft = 0x0402,
        BackRight = 0x0403,
        Front = 0x0404,
        FrontAndBack = 0x0408,
        FrontLeft = 0x0400,
        FrontRight = 0x0401,
        Left = 0x0406,
        None = 0,
        Right = 0x0407,
    }

    public enum EnableCap : uint {
        Blend = 0x0BE2,
        ColorLogicOp = 0x0BF2,
        CullFace = 0x0B44,
        DepthTest = 0x0B71,
        Dither = 0x0BD0,
        LineSmooth = 0x0B20,
        PolygonOffsetFill = 0x8037,
        PolygonOffsetLine = 0x2A02,
        PolygonOffsetPoint = 0x2A01,
        PolygonSmooth = 0x0B41,
        ScissorTest = 0x0C11,
        StencilTest = 0x0B90,
        Texture_1d = 0x0DE0,
        Texture_2d = 0x0DE1,
        VertexArray = 0x8074,
    }

    public enum ErrorCode : uint {
        InvalidEnum = 0x0500,
        InvalidFramebufferOperation = 0x0506,
        InvalidOperation = 0x0502,
        InvalidValue = 0x0501,
        NoError = 0,
        OutOfMemory = 0x0505,
        StackOverflow = 0x0503,
        StackUnderflow = 0x0504,
    }

    public enum FogCoordinatePointerType : uint {
        Float = 0x1406,
        Double = 0x140A,
    }

    public enum FogMode : uint {
        Linear = 0x2601,
    }

    public enum FogPointerTypeEXT : uint {
        Float = 0x1406,
        Double = 0x140A,
    }

    public enum FogPointerTypeIBM : uint {
        Float = 0x1406,
        Double = 0x140A,
    }

    public enum FrontFaceDirection : uint {
        Ccw = 0x0901,
        Cw = 0x0900,
    }

    public enum GetPName : uint {
        AliasedLineWidthRange = 0x846E,
        Blend = 0x0BE2,
        BlendDst = 0x0BE0,
        BlendSrc = 0x0BE1,
        ColorClearValue = 0x0C22,
        ColorLogicOp = 0x0BF2,
        ColorWritemask = 0x0C23,
        CullFace = 0x0B44,
        CullFaceMode = 0x0B45,
        DepthClearValue = 0x0B73,
        DepthFunc = 0x0B74,
        DepthRange = 0x0B70,
        DepthTest = 0x0B71,
        DepthWritemask = 0x0B72,
        Dither = 0x0BD0,
        Doublebuffer = 0x0C32,
        DrawBuffer = 0x0C01,
        FrontFace = 0x0B46,
        LineSmooth = 0x0B20,
        LineSmoothHint = 0x0C52,
        LineWidth = 0x0B21,
        LineWidthGranularity = 0x0B23,
        LineWidthRange = 0x0B22,
        LogicOpMode = 0x0BF0,
        MaxClipDistances = 0x0D32,
        MaxTextureSize = 0x0D33,
        MaxViewportDims = 0x0D3A,
        PackAlignment = 0x0D05,
        PackLsbFirst = 0x0D01,
        PackRowLength = 0x0D02,
        PackSkipPixels = 0x0D04,
        PackSkipRows = 0x0D03,
        PackSwapBytes = 0x0D00,
        PointSize = 0x0B11,
        PointSizeGranularity = 0x0B13,
        PointSizeRange = 0x0B12,
        PolygonMode = 0x0B40,
        PolygonOffsetFactor = 0x8038,
        PolygonOffsetFill = 0x8037,
        PolygonOffsetLine = 0x2A02,
        PolygonOffsetPoint = 0x2A01,
        PolygonOffsetUnits = 0x2A00,
        PolygonSmooth = 0x0B41,
        PolygonSmoothHint = 0x0C53,
        ReadBuffer = 0x0C02,
        ScissorBox = 0x0C10,
        ScissorTest = 0x0C11,
        SmoothLineWidthGranularity = 0x0B23,
        SmoothLineWidthRange = 0x0B22,
        SmoothPointSizeGranularity = 0x0B13,
        SmoothPointSizeRange = 0x0B12,
        StencilClearValue = 0x0B91,
        StencilFail = 0x0B94,
        StencilFunc = 0x0B92,
        StencilPassDepthFail = 0x0B95,
        StencilPassDepthPass = 0x0B96,
        StencilRef = 0x0B97,
        StencilTest = 0x0B90,
        StencilValueMask = 0x0B93,
        StencilWritemask = 0x0B98,
        Stereo = 0x0C33,
        SubpixelBits = 0x0D50,
        Texture_1d = 0x0DE0,
        Texture_2d = 0x0DE1,
        TextureBinding_1d = 0x8068,
        TextureBinding_2d = 0x8069,
        TextureBinding_3d = 0x806A,
        UnpackAlignment = 0x0CF5,
        UnpackLsbFirst = 0x0CF1,
        UnpackRowLength = 0x0CF2,
        UnpackSkipPixels = 0x0CF4,
        UnpackSkipRows = 0x0CF3,
        UnpackSwapBytes = 0x0CF0,
        VertexArray = 0x8074,
        Viewport = 0x0BA2,
    }

    public enum GetTextureParameter : uint {
        TextureAlphaSize = 0x805F,
        TextureBlueSize = 0x805E,
        TextureBorderColor = 0x1004,
        TextureGreenSize = 0x805D,
        TextureHeight = 0x1001,
        TextureInternalFormat = 0x1003,
        TextureMagFilter = 0x2800,
        TextureMinFilter = 0x2801,
        TextureRedSize = 0x805C,
        TextureWidth = 0x1000,
        TextureWrapS = 0x2802,
        TextureWrapT = 0x2803,
    }

    public enum HintMode : uint {
        DontCare = 0x1100,
        Fastest = 0x1101,
        Nicest = 0x1102,
    }

    public enum HintTarget : uint {
        FragmentShaderDerivativeHint = 0x8B8B,
        LineSmoothHint = 0x0C52,
        PolygonSmoothHint = 0x0C53,
        ProgramBinaryRetrievableHint = 0x8257,
        TextureCompressionHint = 0x84EF,
    }

    public enum IndexPointerType : uint {
        Double = 0x140A,
        Float = 0x1406,
        Int = 0x1404,
        Short = 0x1402,
    }

    public enum LightEnvModeSGIX : uint {
        Replace = 0x1E01,
    }

    public enum ListNameType : uint {
        Byte = 0x1400,
        Float = 0x1406,
        Int = 0x1404,
        Short = 0x1402,
        UnsignedByte = 0x1401,
        UnsignedInt = 0x1405,
        UnsignedShort = 0x1403,
    }

    public enum LogicOp : uint {
        And = 0x1501,
        AndInverted = 0x1504,
        AndReverse = 0x1502,
        Clear = 0x1500,
        Copy = 0x1503,
        CopyInverted = 0x150C,
        Equiv = 0x1509,
        Invert = 0x150A,
        Nand = 0x150E,
        Noop = 0x1505,
        Nor = 0x1508,
        Or = 0x1507,
        OrInverted = 0x150D,
        OrReverse = 0x150B,
        Set = 0x150F,
        Xor = 0x1506,
    }

    public enum MapBufferUsageMask : uint {
        ClientStorageBit = 0x0200,
        DynamicStorageBit = 0x0100,
        MapCoherentBit = 0x0080,
        MapFlushExplicitBit = 0x0010,
        MapInvalidateBufferBit = 0x0008,
        MapInvalidateRangeBit = 0x0004,
        MapPersistentBit = 0x0040,
        MapReadBit = 0x0001,
        MapUnsynchronizedBit = 0x0020,
        MapWriteBit = 0x0002,
    }

    public enum MatrixMode : uint {
        Texture = 0x1702,
    }

    public enum MemoryBarrierMask : uint {
        AllBarrierBits = 0xFFFFFFFF,
        AtomicCounterBarrierBit = 0x00001000,
        BufferUpdateBarrierBit = 0x00000200,
        ClientMappedBufferBarrierBit = 0x00004000,
        CommandBarrierBit = 0x00000040,
        ElementArrayBarrierBit = 0x00000002,
        FramebufferBarrierBit = 0x00000400,
        PixelBufferBarrierBit = 0x00000080,
        QueryBufferBarrierBit = 0x00008000,
        ShaderImageAccessBarrierBit = 0x00000020,
        ShaderStorageBarrierBit = 0x00002000,
        TextureFetchBarrierBit = 0x00000008,
        TextureUpdateBarrierBit = 0x00000100,
        TransformFeedbackBarrierBit = 0x00000800,
        UniformBarrierBit = 0x00000004,
        VertexAttribArrayBarrierBit = 0x00000001,
    }

    public enum MeshMode1 : uint {
        Line = 0x1B01,
        Point = 0x1B00,
    }

    public enum MeshMode2 : uint {
        Fill = 0x1B02,
        Line = 0x1B01,
        Point = 0x1B00,
    }

    public enum NormalPointerType : uint {
        Byte = 0x1400,
        Double = 0x140A,
        Float = 0x1406,
        Int = 0x1404,
        Short = 0x1402,
    }

    public enum PixelCopyType : uint {
        Color = 0x1800,
        Depth = 0x1801,
        Stencil = 0x1802,
    }

    public enum PixelFormat : uint {
        Alpha = 0x1906,
        Blue = 0x1905,
        DepthComponent = 0x1902,
        Green = 0x1904,
        Red = 0x1903,
        RGB = 0x1907,
        RGBA = 0x1908,
        StencilIndex = 0x1901,
        UnsignedInt = 0x1405,
        UnsignedShort = 0x1403,
    }

    public enum InternalFormat : uint {
        R3G3B2 = 0x2A10,
        RGB10 = 0x8052,
        RGB10A2 = 0x8059,
        RGB12 = 0x8053,
        RGB16 = 0x8054,
        RGB4 = 0x804F,
        RGB5 = 0x8050,
        RGB5A1 = 0x8057,
        RGB8 = 0x8051,
        RGBA12 = 0x805A,
        RGBA16 = 0x805B,
        RGBA2 = 0x8055,
        RGBA4 = 0x8056,
        RGBA8 = 0x8058,
    }

    public enum PixelStoreParameter : uint {
        PackAlignment = 0x0D05,
        PackImageHeight = 0x806C,
        PackLsbFirst = 0x0D01,
        PackRowLength = 0x0D02,
        PackSkipImages = 0x806B,
        PackSkipPixels = 0x0D04,
        PackSkipRows = 0x0D03,
        PackSwapBytes = 0x0D00,
        UnpackAlignment = 0x0CF5,
        UnpackImageHeight = 0x806E,
        UnpackLsbFirst = 0x0CF1,
        UnpackRowLength = 0x0CF2,
        UnpackSkipImages = 0x806D,
        UnpackSkipPixels = 0x0CF4,
        UnpackSkipRows = 0x0CF3,
        UnpackSwapBytes = 0x0CF0,
    }

    public enum PixelTexGenMode : uint {
        None = 0,
        RGB = 0x1907,
        RGBA = 0x1908,
    }

    public enum PixelType : uint {
        Byte = 0x1400,
        Float = 0x1406,
        Int = 0x1404,
        Short = 0x1402,
        UnsignedByte = 0x1401,
        UnsignedByte_3_3_2 = 0x8032,
        UnsignedInt = 0x1405,
        UnsignedInt_10_10_10_2 = 0x8036,
        UnsignedInt_8_8_8_8 = 0x8035,
        UnsignedShort = 0x1403,
        UnsignedShort_4_4_4_4 = 0x8033,
        UnsignedShort_5_5_5_1 = 0x8034,
    }

    public enum PointParameterNameSGIS : uint {
        PointFadeThresholdSize = 0x8128,
    }

    public enum PolygonMode : uint {
        Fill = 0x1B02,
        Line = 0x1B01,
        Point = 0x1B00,
    }

    public enum PrimitiveType : uint {
        Lines = 0x0001,
        LinesAdjacency = 0x000A,
        LineLoop = 0x0002,
        LineStrip = 0x0003,
        LineStripAdjacency = 0x000B,
        Patches = 0x000E,
        Points = 0x0000,
        Quads = 0x0007,
        Triangles = 0x0004,
        TrianglesAdjacency = 0x000C,
        TriangleFan = 0x0006,
        TriangleStrip = 0x0005,
        TriangleStripAdjacency = 0x000D,
    }

    public enum ReadBufferMode : uint {
        Back = 0x0405,
        BackLeft = 0x0402,
        BackRight = 0x0403,
        Front = 0x0404,
        FrontLeft = 0x0400,
        FrontRight = 0x0401,
        Left = 0x0406,
        Right = 0x0407,
    }

    public enum StencilFunction : uint {
        Always = 0x0207,
        Equal = 0x0202,
        Gequal = 0x0206,
        Greater = 0x0204,
        Lequal = 0x0203,
        Less = 0x0201,
        Never = 0x0200,
        Notequal = 0x0205,
    }

    public enum StencilOp : uint {
        Decr = 0x1E03,
        Incr = 0x1E02,
        Invert = 0x150A,
        Keep = 0x1E00,
        Replace = 0x1E01,
        Zero = 0,
    }

    public enum StringName : uint {
        Extensions = 0x1F03,
        Renderer = 0x1F01,
        Vendor = 0x1F00,
        Version = 0x1F02,
    }

    public enum TexCoordPointerType : uint {
        Double = 0x140A,
        Float = 0x1406,
        Int = 0x1404,
        Short = 0x1402,
    }

    public enum TextureEnvMode : uint {
        Blend = 0x0BE2,
    }

    public enum TextureMagFilter : uint {
        Linear = 0x2601,
        Nearest = 0x2600,
    }

    public enum TextureMinFilter : uint {
        Linear = 0x2601,
        LinearMipmapLinear = 0x2703,
        LinearMipmapNearest = 0x2701,
        Nearest = 0x2600,
        NearestMipmapLinear = 0x2702,
        NearestMipmapNearest = 0x2700,
    }

    public enum TextureParameterName : uint {
        TextureBorderColor = 0x1004,
        TextureMagFilter = 0x2800,
        TextureMinFilter = 0x2801,
        TextureWrapR = 0x8072,
        TextureWrapS = 0x2802,
        TextureWrapT = 0x2803,
    }

    public enum TextureTarget : uint {
        ProxyTexture_1d = 0x8063,
        ProxyTexture_2d = 0x8064,
        ProxyTexture_3d = 0x8070,
        Texture_1d = 0x0DE0,
        Texture_2d = 0x0DE1,
        Texture_3d = 0x806F,
        TextureBaseLevel = 0x813C,
        TextureMaxLevel = 0x813D,
        TextureMaxLod = 0x813B,
        TextureMinLod = 0x813A,
    }

    public enum TextureWrapMode : uint {
        ClampToBorder = 0x812D,
        ClampToEdge = 0x812F,
        Repeat = 0x2901,
    }

    public enum UseProgramStageMask : uint {
        VertexShaderBit = 0x00000001,
        FragmentShaderBit = 0x00000002,
        GeometryShaderBit = 0x00000004,
        TessControlShaderBit = 0x00000008,
        TessEvaluationShaderBit = 0x00000010,
        ComputeShaderBit = 0x00000020,
        AllShaderBits = 0xFFFFFFFF,
    }

    public enum VertexPointerType : uint {
        Double = 0x140A,
        Float = 0x1406,
        Int = 0x1404,
        Short = 0x1402,
    }

    public enum TypeEnum : uint {
        QueryWait = 0x8E13,
        QueryNoWait = 0x8E14,
        QueryByRegionWait = 0x8E15,
        QueryByRegionNoWait = 0x8E16,
    }

    public enum BufferTarget : uint {
        ArrayBuffer = 0x8892,
        AtomicCounterBuffer = 0x92C0,
        CopyReadBuffer = 0x8F36,
        CopyWriteBuffer = 0x8F37,
        DrawIndirectBuffer = 0x8F3F,
        DispatchIndirectBuffer = 0x90EE,
        ElementArrayBuffer = 0x8893,
        PixelPackBuffer = 0x88EB,
        PixelUnpackBuffer = 0x88EC,
        QueryBuffer = 0x9192,
        ShaderStorageBuffer = 0x90D2,
        TextureBuffer = 0x8C2A,
        TransformFeedbackBuffer = 0x8C8E,
        UniformBuffer = 0x8A11,
    }

    public enum FramebufferTarget : uint {
        DrawFramebuffer = 0x8CA9,
        ReadFramebuffer = 0x8CA8,
        Framebuffer = 0x8D40,
    }

    public enum RenderbufferTarget : uint {
        Renderbuffer = 0x8D41,
    }

    public enum BlendEquationMode : uint {
        FuncAdd = 0x8006,
        FuncSubtract = 0x800A,
        FuncReverseSubtract = 0x800B,
        Min = 0x8007,
        Max = 0x8008,
    }

    public enum BufferUsage : uint {
        StreamDraw = 0x88E0,
        StreamRead = 0x88E1,
        StreamCopy = 0x88E2,
        StaticDraw = 0x88E4,
        StaticRead = 0x88E5,
        StaticCopy = 0x88E6,
        DynamicDraw = 0x88E8,
        DynamicRead = 0x88E9,
        DynamicCopy = 0x88EA,
    }

    public enum ClampColorTarget : uint {
        ClampReadColor = 0x891C,
    }

    public enum DrawElementsType : uint {
        UnsignedByte = 0x1401,
        UnsignedShort = 0x1403,
        UnsignedInt = 0x1405,
    }

    public enum FramebufferAttachment : uint {
        ColorAttachment0 = 0x8CE0,
        ColorAttachment1 = 0x8CE1,
        ColorAttachment2 = 0x8CE2,
        ColorAttachment3 = 0x8CE3,
        ColorAttachment4 = 0x8CE4,
        ColorAttachment5 = 0x8CE5,
        ColorAttachment6 = 0x8CE6,
        ColorAttachment7 = 0x8CE7,
        ColorAttachment8 = 0x8CE8,
        ColorAttachment9 = 0x8CE9,
        ColorAttachment11 = 0x8CEB,
        ColorAttachment12 = 0x8CEC,
        ColorAttachment13 = 0x8CED,
        ColorAttachment14 = 0x8CEE,
        ColorAttachment15 = 0x8CEF,
        ColorAttachment16 = 0x8CF0,
        ColorAttachment17 = 0x8CF1,
        ColorAttachment18 = 0x8CF2,
        ColorAttachment19 = 0x8CF3,
        ColorAttachment21 = 0x8CF5,
        ColorAttachment22 = 0x8CF6,
        ColorAttachment23 = 0x8CF7,
        ColorAttachment24 = 0x8CF8,
        ColorAttachment25 = 0x8CF9,
        ColorAttachment26 = 0x8CFA,
        ColorAttachment27 = 0x8CFB,
        ColorAttachment28 = 0x8CFC,
        ColorAttachment29 = 0x8CFD,
        ColorAttachment30 = 0x8CFE,
        ColorAttachment31 = 0x8CFF,
        DepthAttachment = 0x8D00,
        StencilAttachment = 0x8D20,
        DepthStencilAttachment = 0x821A,
    }

    public enum TextureUnit : uint {
        Texture0 = 0x84C0,
        Texture1 = 0x84C1,
        Texture2 = 0x84C2,
        Texture3 = 0x84C3,
        Texture4 = 0x84C4,
        Texture5 = 0x84C5,
        Texture6 = 0x84C6,
        Texture7 = 0x84C7,
        Texture8 = 0x84C8,
        Texture9 = 0x84C9,
        Texture10 = 0x84CA,
        Texture11 = 0x84CB,
        Texture12 = 0x84CC,
        Texture13 = 0x84CD,
        Texture14 = 0x84CE,
        Texture15 = 0x84CF,
        Texture16 = 0x84D0,
        Texture17 = 0x84D1,
        Texture18 = 0x84D2,
        Texture19 = 0x84D3,
        Texture20 = 0x84D4,
        Texture21 = 0x84D5,
        Texture22 = 0x84D6,
        Texture23 = 0x84D7,
        Texture24 = 0x84D8,
        Texture25 = 0x84D9,
        Texture26 = 0x84DA,
        Texture27 = 0x84DB,
        Texture28 = 0x84DC,
        Texture29 = 0x84DD,
        Texture30 = 0x84DE,
        Texture31 = 0x84DF,
    }

    public enum PixelInternalFormat : uint {
        CompressedRGB8Etc2 = 0x9274,
        CompressedSRGB8Etc2 = 0x9275,
        CompressedRGB8PunchthroughAlpha1Etc2 = 0x9276,
        CompressedSRGB8PunchthroughAlpha1Etc2 = 0x9277,
        CompressedRGBA8Etc2Eac = 0x9278,
        CompressedSRGB8Alpha8Etc2Eac = 0x9279,
        CompressedR11Eac = 0x9270,
        CompressedSignedR11Eac = 0x9271,
        CompressedRG11Eac = 0x9272,
        CompressedSignedRG11Eac = 0x9273,
    }

    public enum VertexAttribEnum : uint {
        Byte = 0x1400,
        UnsignedByte = 0x1401,
        Short = 0x1402,
        UnsignedShort = 0x1403,
        Int = 0x1404,
        UnsignedInt = 0x1405,
    }

    public enum VertexAttribPointerType : uint {
        Byte = 0x1400,
        UnsignedByte = 0x1401,
        Short = 0x1402,
        UnsignedShort = 0x1403,
        Int = 0x1404,
        UnsignedInt = 0x1405,
        HalfFloat = 0x140B,
        Float = 0x1406,
        Double = 0x140A,
        Fixed = 0x140C,
        Int_2_10_10_10Rev = 0x8D9F,
        UnsignedInt_2_10_10_10Rev = 0x8368,
        UnsignedInt_10f_11f_11fRev = 0x8C3B,
    }

    public enum BufferAccess : uint {
        ReadOnly = 0x88B8,
        WriteOnly = 0x88B9,
        ReadWrite = 0x88BA,
    }

    public enum PointParameterName : uint {
        PointFadeThresholdSize = 0x8128,
        PointSpriteCoordOrigin = 0x8CA0,
    }

    public enum BufferPName : uint {
        BufferAccess = 0x88BB,
        BufferAccessFlags = 0x911F,
        BufferImmutableStorage = 0x821F,
        BufferMapped = 0x88BC,
        BufferMapLength = 0x9120,
        BufferMapOffset = 0x9121,
        BufferSize = 0x8764,
        BufferStorageFlags = 0x8220,
        BufferUsage = 0x8765,
    }

    public enum VertexAttribProperty : uint {
        VertexAttribArrayBufferBinding = 0x889F,
        VertexAttribArrayEnabled = 0x8622,
        VertexAttribArraySize = 0x8623,
        VertexAttribArrayStride = 0x8624,
        VertexAttribArrayType = 0x8625,
        VertexAttribArrayNormalized = 0x886A,
        VertexAttribArrayInteger = 0x88FD,
        VertexAttribArrayDivisor = 0x88FE,
        CurrentVertexAttrib = 0x8626,
    }

    public enum ProgramParameterPName : uint {
        ProgramBinaryRetrievableHint = 0x8257,
        ProgramSeparable = 0x8258,
    }

    public enum GetPointervPName : uint {
        DebugCallbackFunction = 0x8244,
        DebugCallbackUserParam = 0x8245,
    }

    public enum VertexAttribPointerProperty : uint {
        VertexAttribArrayPointer = 0x8645,
    }

    public enum DebugMessageSource : uint {
        DebugSourceApi = 0x8246,
        DebugSourceWindowSystem = 0x8247,
        DebugSourceShaderCompiler = 0x8248,
        DebugSourceThirdParty = 0x8249,
        DebugSourceApplication = 0x824A,
        DebugSourceOther = 0x824B,
    }

    public enum DebugMessageType : uint {
        DebugTypeError = 0x824C,
        DebugTypeDeprecatedBehavior = 0x824D,
        DebugTypeUndefinedBehavior = 0x824E,
        DebugTypePortability = 0x824F,
        DebugTypePerformance = 0x8250,
        DebugTypeMarker = 0x8268,
        DebugTypePushGroup = 0x8269,
        DebugTypePopGroup = 0x826A,
        DebugTypeOther = 0x8251,
    }

    public enum DebugMessageSeverity : uint {
        DebugSeverityHigh = 0x9146,
        DebugSeverityMedium = 0x9147,
        DebugSeverityLow = 0x9148,
        DebugSeverityNotification = 0x826B,
    }

    public enum QueryMode : uint {
        SamplesPassed = 0x8914,
        AnySamplesPassed = 0x8C2F,
        AnySamplesPassedConservative = 0x8D6A,
        PrimitivesGenerated = 0x8C87,
        TransformFeedbackPrimitivesWritten = 0x8C88,
        TimeElapsed = 0x88BF,
    }

    public enum TransformFeedbackMode : uint {
        Points = 0x0000,
        Lines = 0x0001,
        Triangles = 0x0004,
    }

    public enum ShaderType : uint {
        ComputeShader = 0x91B9,
        VertexShader = 0x8B31,
        TessControlShader = 0x8E88,
        TessEvaluationShader = 0x8E87,
        GeometryShader = 0x8DD9,
        FragmentShader = 0x8B30,
    }

    public enum BufferAccessMask : uint {
        MapReadBit = 0x0001,
        MapWriteBit = 0x0002,
        MapInvalidateRangeBit = 0x0004,
        MapInvalidateBufferBit = 0x0008,
        MapFlushExplicitBit = 0x0010,
        MapUnsynchronizedBit = 0x0020,
    }

    public enum ProgramParameter : uint {
        DeleteStatus = 0x8B80,
        LinkStatus = 0x8B82,
        ValidateStatus = 0x8B83,
        InfoLogLength = 0x8B84,
        AttachedShaders = 0x8B85,
        ActiveAtomicCounterBuffers = 0x92D9,
        ActiveAttributes = 0x8B89,
        ActiveAttributeMaxLength = 0x8B8A,
        ActiveUniforms = 0x8B86,
        ActiveUniformBlocks = 0x8A36,
        ActiveUniformBlockMaxNameLength = 0x8A35,
        ActiveUniformMaxLength = 0x8B87,
        ComputeWorkGroupSize = 0x8267,
        ProgramBinaryLength = 0x8741,
        TransformFeedbackBufferMode = 0x8C7F,
        TransformFeedbackVaryings = 0x8C83,
        TransformFeedbackVaryingMaxLength = 0x8C76,
        GeometryVerticesOut = 0x8916,
        GeometryInputType = 0x8917,
        GeometryOutputType = 0x8918,
    }

    public enum ShaderParameter : uint {
        ShaderType = 0x8B4F,
        DeleteStatus = 0x8B80,
        CompileStatus = 0x8B81,
        InfoLogLength = 0x8B84,
        ShaderSourceLength = 0x8B88,
    }

}
