//autogenerated on 8/22/2016 7:39:04 PM
using System;

namespace CSGL.Vulkan {
    [Flags]
    public enum VkFramebufferCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkQueryPoolCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkRenderPassCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkSamplerCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineLayoutCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineCacheCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineDepthStencilStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineDynamicStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineColorBlendStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineMultisampleStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineRasterizationStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineViewportStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineTessellationStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineInputAssemblyStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineVertexInputStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineShaderStageCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDescriptorSetLayoutCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkBufferViewCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkInstanceCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDeviceCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDeviceQueueCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkQueueFlags : uint {
        None = 0,
        QueueGraphicsBit = 1,
        QueueComputeBit = 2,
        QueueTransferBit = 4,
        QueueSparseBindingBit = 8,
    }

    [Flags]
    public enum VkMemoryPropertyFlags : uint {
        None = 0,
        MemoryPropertyDeviceLocalBit = 1,
        MemoryPropertyHostVisibleBit = 2,
        MemoryPropertyHostCoherentBit = 4,
        MemoryPropertyHostCachedBit = 8,
        MemoryPropertyLazilyAllocatedBit = 16,
    }

    [Flags]
    public enum VkMemoryHeapFlags : uint {
        None = 0,
        MemoryHeapDeviceLocalBit = 1,
    }

    [Flags]
    public enum VkAccessFlags : uint {
        None = 0,
        AccessIndirectCommandReadBit = 1,
        AccessIndexReadBit = 2,
        AccessVertexAttributeReadBit = 4,
        AccessUniformReadBit = 8,
        AccessInputAttachmentReadBit = 16,
        AccessShaderReadBit = 32,
        AccessShaderWriteBit = 64,
        AccessColorAttachmentReadBit = 128,
        AccessColorAttachmentWriteBit = 256,
        AccessDepthStencilAttachmentReadBit = 512,
        AccessDepthStencilAttachmentWriteBit = 1024,
        AccessTransferReadBit = 2048,
        AccessTransferWriteBit = 4096,
        AccessHostReadBit = 8192,
        AccessHostWriteBit = 16384,
        AccessMemoryReadBit = 32768,
        AccessMemoryWriteBit = 65536,
    }

    [Flags]
    public enum VkBufferUsageFlags : uint {
        None = 0,
        BufferUsageTransferSrcBit = 1,
        BufferUsageTransferDstBit = 2,
        BufferUsageUniformTexelBufferBit = 4,
        BufferUsageStorageTexelBufferBit = 8,
        BufferUsageUniformBufferBit = 16,
        BufferUsageStorageBufferBit = 32,
        BufferUsageIndexBufferBit = 64,
        BufferUsageVertexBufferBit = 128,
        BufferUsageIndirectBufferBit = 256,
    }

    [Flags]
    public enum VkBufferCreateFlags : uint {
        None = 0,
        BufferCreateSparseBindingBit = 1,
        BufferCreateSparseResidencyBit = 2,
        BufferCreateSparseAliasedBit = 4,
    }

    [Flags]
    public enum VkShaderStageFlags : uint {
        None = 0,
        ShaderStageVertexBit = 1,
        ShaderStageTessellationControlBit = 2,
        ShaderStageTessellationEvaluationBit = 4,
        ShaderStageGeometryBit = 8,
        ShaderStageFragmentBit = 16,
        ShaderStageComputeBit = 32,
        ShaderStageAllGraphics = 0x0000001F,
        ShaderStageAll = 0x7FFFFFFF,
    }

    [Flags]
    public enum VkImageUsageFlags : uint {
        None = 0,
        ImageUsageTransferSrcBit = 1,
        ImageUsageTransferDstBit = 2,
        ImageUsageSampledBit = 4,
        ImageUsageStorageBit = 8,
        ImageUsageColorAttachmentBit = 16,
        ImageUsageDepthStencilAttachmentBit = 32,
        ImageUsageTransientAttachmentBit = 64,
        ImageUsageInputAttachmentBit = 128,
    }

    [Flags]
    public enum VkImageCreateFlags : uint {
        None = 0,
        ImageCreateSparseBindingBit = 1,
        ImageCreateSparseResidencyBit = 2,
        ImageCreateSparseAliasedBit = 4,
        ImageCreateMutableFormatBit = 8,
        ImageCreateCubeCompatibleBit = 16,
    }

    [Flags]
    public enum VkImageViewCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineCreateFlags : uint {
        None = 0,
        PipelineCreateDisableOptimizationBit = 1,
        PipelineCreateAllowDerivativesBit = 2,
        PipelineCreateDerivativeBit = 4,
    }

    [Flags]
    public enum VkColorComponentFlags : uint {
        None = 0,
        ColorComponentRBit = 1,
        ColorComponentGBit = 2,
        ColorComponentBBit = 4,
        ColorComponentABit = 8,
    }

    [Flags]
    public enum VkFenceCreateFlags : uint {
        None = 0,
        FenceCreateSignaledBit = 1,
    }

    [Flags]
    public enum VkSemaphoreCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkFormatFeatureFlags : uint {
        None = 0,
        FormatFeatureSampledImageBit = 1,
        FormatFeatureStorageImageBit = 2,
        FormatFeatureStorageImageAtomicBit = 4,
        FormatFeatureUniformTexelBufferBit = 8,
        FormatFeatureStorageTexelBufferBit = 16,
        FormatFeatureStorageTexelBufferAtomicBit = 32,
        FormatFeatureVertexBufferBit = 64,
        FormatFeatureColorAttachmentBit = 128,
        FormatFeatureColorAttachmentBlendBit = 256,
        FormatFeatureDepthStencilAttachmentBit = 512,
        FormatFeatureBlitSrcBit = 1024,
        FormatFeatureBlitDstBit = 2048,
        FormatFeatureSampledImageFilterLinearBit = 4096,
    }

    [Flags]
    public enum VkQueryControlFlags : uint {
        None = 0,
        QueryControlPreciseBit = 1,
    }

    [Flags]
    public enum VkQueryResultFlags : uint {
        None = 0,
        QueryResult64Bit = 1,
        QueryResultWaitBit = 2,
        QueryResultWithAvailabilityBit = 4,
        QueryResultPartialBit = 8,
    }

    [Flags]
    public enum VkShaderModuleCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkEventCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkCommandPoolCreateFlags : uint {
        None = 0,
        CommandPoolCreateTransientBit = 1,
        CommandPoolCreateResetCommandBufferBit = 2,
    }

    [Flags]
    public enum VkCommandPoolResetFlags : uint {
        None = 0,
        CommandPoolResetReleaseResourcesBit = 1,
    }

    [Flags]
    public enum VkCommandBufferResetFlags : uint {
        None = 0,
        CommandBufferResetReleaseResourcesBit = 1,
    }

    [Flags]
    public enum VkCommandBufferUsageFlags : uint {
        None = 0,
        CommandBufferUsageOneTimeSubmitBit = 1,
        CommandBufferUsageRenderPassContinueBit = 2,
        CommandBufferUsageSimultaneousUseBit = 4,
    }

    [Flags]
    public enum VkQueryPipelineStatisticFlags : uint {
        None = 0,
        QueryPipelineStatisticInputAssemblyVerticesBit = 1,
        QueryPipelineStatisticInputAssemblyPrimitivesBit = 2,
        QueryPipelineStatisticVertexShaderInvocationsBit = 4,
        QueryPipelineStatisticGeometryShaderInvocationsBit = 8,
        QueryPipelineStatisticGeometryShaderPrimitivesBit = 16,
        QueryPipelineStatisticClippingInvocationsBit = 32,
        QueryPipelineStatisticClippingPrimitivesBit = 64,
        QueryPipelineStatisticFragmentShaderInvocationsBit = 128,
        QueryPipelineStatisticTessellationControlShaderPatchesBit = 256,
        QueryPipelineStatisticTessellationEvaluationShaderInvocationsBit = 512,
        QueryPipelineStatisticComputeShaderInvocationsBit = 1024,
    }

    [Flags]
    public enum VkMemoryMapFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkImageAspectFlags : uint {
        None = 0,
        ImageAspectColorBit = 1,
        ImageAspectDepthBit = 2,
        ImageAspectStencilBit = 4,
        ImageAspectMetadataBit = 8,
    }

    [Flags]
    public enum VkSparseMemoryBindFlags : uint {
        None = 0,
        SparseMemoryBindMetadataBit = 1,
    }

    [Flags]
    public enum VkSparseImageFormatFlags : uint {
        None = 0,
        SparseImageFormatSingleMiptailBit = 1,
        SparseImageFormatAlignedMipSizeBit = 2,
        SparseImageFormatNonstandardBlockSizeBit = 4,
    }

    [Flags]
    public enum VkSubpassDescriptionFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineStageFlags : uint {
        None = 0,
        PipelineStageTopOfPipeBit = 1,
        PipelineStageDrawIndirectBit = 2,
        PipelineStageVertexInputBit = 4,
        PipelineStageVertexShaderBit = 8,
        PipelineStageTessellationControlShaderBit = 16,
        PipelineStageTessellationEvaluationShaderBit = 32,
        PipelineStageGeometryShaderBit = 64,
        PipelineStageFragmentShaderBit = 128,
        PipelineStageEarlyFragmentTestsBit = 256,
        PipelineStageLateFragmentTestsBit = 512,
        PipelineStageColorAttachmentOutputBit = 1024,
        PipelineStageComputeShaderBit = 2048,
        PipelineStageTransferBit = 4096,
        PipelineStageBottomOfPipeBit = 8192,
        PipelineStageHostBit = 16384,
        PipelineStageAllGraphicsBit = 32768,
        PipelineStageAllCommandsBit = 65536,
    }

    [Flags]
    public enum VkSampleCountFlags : uint {
        None = 0,
        SampleCount1Bit = 1,
        SampleCount2Bit = 2,
        SampleCount4Bit = 4,
        SampleCount8Bit = 8,
        SampleCount16Bit = 16,
        SampleCount32Bit = 32,
        SampleCount64Bit = 64,
    }

    [Flags]
    public enum VkAttachmentDescriptionFlags : uint {
        None = 0,
        AttachmentDescriptionMayAliasBit = 1,
    }

    [Flags]
    public enum VkStencilFaceFlags : uint {
        None = 0,
        StencilFaceFrontBit = 1,
        StencilFaceBackBit = 2,
        StencilFrontAndBack = 0x00000003,
    }

    [Flags]
    public enum VkCullModeFlags : uint {
        None = 0,
        CullModeNone = 0,
        CullModeFrontBit = 1,
        CullModeBackBit = 2,
        CullModeFrontAndBack = 0x00000003,
    }

    [Flags]
    public enum VkDescriptorPoolCreateFlags : uint {
        None = 0,
        DescriptorPoolCreateFreeDescriptorSetBit = 1,
    }

    [Flags]
    public enum VkDescriptorPoolResetFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDependencyFlags : uint {
        None = 0,
        DependencyByRegionBit = 1,
    }

    [Flags]
    public enum VkCompositeAlphaFlagsKHR : uint {
        None = 0,
        CompositeAlphaOpaqueBitKhr = 1,
        CompositeAlphaPreMultipliedBitKhr = 2,
        CompositeAlphaPostMultipliedBitKhr = 4,
        CompositeAlphaInheritBitKhr = 8,
    }

    [Flags]
    public enum VkDisplayPlaneAlphaFlagsKHR : uint {
        None = 0,
        DisplayPlaneAlphaOpaqueBitKhr = 1,
        DisplayPlaneAlphaGlobalBitKhr = 2,
        DisplayPlaneAlphaPerPixelBitKhr = 4,
        DisplayPlaneAlphaPerPixelPremultipliedBitKhr = 8,
    }

    [Flags]
    public enum VkSurfaceTransformFlagsKHR : uint {
        None = 0,
        SurfaceTransformIdentityBitKhr = 1,
        SurfaceTransformRotate90BitKhr = 2,
        SurfaceTransformRotate180BitKhr = 4,
        SurfaceTransformRotate270BitKhr = 8,
        SurfaceTransformHorizontalMirrorBitKhr = 16,
        SurfaceTransformHorizontalMirrorRotate90BitKhr = 32,
        SurfaceTransformHorizontalMirrorRotate180BitKhr = 64,
        SurfaceTransformHorizontalMirrorRotate270BitKhr = 128,
        SurfaceTransformInheritBitKhr = 256,
    }

    [Flags]
    public enum VkSwapchainCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkDisplayModeCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkDisplaySurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkAndroidSurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkMirSurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkWaylandSurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkWin32SurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkXlibSurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkXcbSurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkDebugReportFlagsEXT : uint {
        None = 0,
        DebugReportInformationBitExt = 1,
        DebugReportWarningBitExt = 2,
        DebugReportPerformanceWarningBitExt = 4,
        DebugReportErrorBitExt = 8,
        DebugReportDebugBitExt = 16,
    }

    public enum VkAttachmentLoadOp {
        AttachmentLoadOpLoad = 0,
        AttachmentLoadOpClear = 1,
        AttachmentLoadOpDontCare = 2,
    }

    public enum VkAttachmentStoreOp {
        AttachmentStoreOpStore = 0,
        AttachmentStoreOpDontCare = 1,
    }

    public enum VkBlendFactor {
        BlendFactorZero = 0,
        BlendFactorOne = 1,
        BlendFactorSrcColor = 2,
        BlendFactorOneMinusSrcColor = 3,
        BlendFactorDstColor = 4,
        BlendFactorOneMinusDstColor = 5,
        BlendFactorSrcAlpha = 6,
        BlendFactorOneMinusSrcAlpha = 7,
        BlendFactorDstAlpha = 8,
        BlendFactorOneMinusDstAlpha = 9,
        BlendFactorConstantColor = 10,
        BlendFactorOneMinusConstantColor = 11,
        BlendFactorConstantAlpha = 12,
        BlendFactorOneMinusConstantAlpha = 13,
        BlendFactorSrcAlphaSaturate = 14,
        BlendFactorSrc1Color = 15,
        BlendFactorOneMinusSrc1Color = 16,
        BlendFactorSrc1Alpha = 17,
        BlendFactorOneMinusSrc1Alpha = 18,
    }

    public enum VkBlendOp {
        BlendOpAdd = 0,
        BlendOpSubtract = 1,
        BlendOpReverseSubtract = 2,
        BlendOpMin = 3,
        BlendOpMax = 4,
    }

    public enum VkBorderColor {
        BorderColorFloatTransparentBlack = 0,
        BorderColorIntTransparentBlack = 1,
        BorderColorFloatOpaqueBlack = 2,
        BorderColorIntOpaqueBlack = 3,
        BorderColorFloatOpaqueWhite = 4,
        BorderColorIntOpaqueWhite = 5,
    }

    public enum VkPipelineCacheHeaderVersion {
        PipelineCacheHeaderVersionOne = 1,
    }

    public enum VkComponentSwizzle {
        ComponentSwizzleIdentity = 0,
        ComponentSwizzleZero = 1,
        ComponentSwizzleOne = 2,
        ComponentSwizzleR = 3,
        ComponentSwizzleG = 4,
        ComponentSwizzleB = 5,
        ComponentSwizzleA = 6,
    }

    public enum VkCommandBufferLevel {
        CommandBufferLevelPrimary = 0,
        CommandBufferLevelSecondary = 1,
    }

    public enum VkCompareOp {
        CompareOpNever = 0,
        CompareOpLess = 1,
        CompareOpEqual = 2,
        CompareOpLessOrEqual = 3,
        CompareOpGreater = 4,
        CompareOpNotEqual = 5,
        CompareOpGreaterOrEqual = 6,
        CompareOpAlways = 7,
    }

    public enum VkDescriptorType {
        DescriptorTypeSampler = 0,
        DescriptorTypeCombinedImageSampler = 1,
        DescriptorTypeSampledImage = 2,
        DescriptorTypeStorageImage = 3,
        DescriptorTypeUniformTexelBuffer = 4,
        DescriptorTypeStorageTexelBuffer = 5,
        DescriptorTypeUniformBuffer = 6,
        DescriptorTypeStorageBuffer = 7,
        DescriptorTypeUniformBufferDynamic = 8,
        DescriptorTypeStorageBufferDynamic = 9,
        DescriptorTypeInputAttachment = 10,
    }

    public enum VkDynamicState {
        DynamicStateViewport = 0,
        DynamicStateScissor = 1,
        DynamicStateLineWidth = 2,
        DynamicStateDepthBias = 3,
        DynamicStateBlendConstants = 4,
        DynamicStateDepthBounds = 5,
        DynamicStateStencilCompareMask = 6,
        DynamicStateStencilWriteMask = 7,
        DynamicStateStencilReference = 8,
    }

    public enum VkPolygonMode {
        PolygonModeFill = 0,
        PolygonModeLine = 1,
        PolygonModePoint = 2,
    }

    public enum VkFormat {
        FormatUndefined = 0,
        FormatR4g4UnormPack8 = 1,
        FormatR4g4b4a4UnormPack16 = 2,
        FormatB4g4r4a4UnormPack16 = 3,
        FormatR5g6b5UnormPack16 = 4,
        FormatB5g6r5UnormPack16 = 5,
        FormatR5g5b5a1UnormPack16 = 6,
        FormatB5g5r5a1UnormPack16 = 7,
        FormatA1r5g5b5UnormPack16 = 8,
        FormatR8Unorm = 9,
        FormatR8Snorm = 10,
        FormatR8Uscaled = 11,
        FormatR8Sscaled = 12,
        FormatR8Uint = 13,
        FormatR8Sint = 14,
        FormatR8Srgb = 15,
        FormatR8g8Unorm = 16,
        FormatR8g8Snorm = 17,
        FormatR8g8Uscaled = 18,
        FormatR8g8Sscaled = 19,
        FormatR8g8Uint = 20,
        FormatR8g8Sint = 21,
        FormatR8g8Srgb = 22,
        FormatR8g8b8Unorm = 23,
        FormatR8g8b8Snorm = 24,
        FormatR8g8b8Uscaled = 25,
        FormatR8g8b8Sscaled = 26,
        FormatR8g8b8Uint = 27,
        FormatR8g8b8Sint = 28,
        FormatR8g8b8Srgb = 29,
        FormatB8g8r8Unorm = 30,
        FormatB8g8r8Snorm = 31,
        FormatB8g8r8Uscaled = 32,
        FormatB8g8r8Sscaled = 33,
        FormatB8g8r8Uint = 34,
        FormatB8g8r8Sint = 35,
        FormatB8g8r8Srgb = 36,
        FormatR8g8b8a8Unorm = 37,
        FormatR8g8b8a8Snorm = 38,
        FormatR8g8b8a8Uscaled = 39,
        FormatR8g8b8a8Sscaled = 40,
        FormatR8g8b8a8Uint = 41,
        FormatR8g8b8a8Sint = 42,
        FormatR8g8b8a8Srgb = 43,
        FormatB8g8r8a8Unorm = 44,
        FormatB8g8r8a8Snorm = 45,
        FormatB8g8r8a8Uscaled = 46,
        FormatB8g8r8a8Sscaled = 47,
        FormatB8g8r8a8Uint = 48,
        FormatB8g8r8a8Sint = 49,
        FormatB8g8r8a8Srgb = 50,
        FormatA8b8g8r8UnormPack32 = 51,
        FormatA8b8g8r8SnormPack32 = 52,
        FormatA8b8g8r8UscaledPack32 = 53,
        FormatA8b8g8r8SscaledPack32 = 54,
        FormatA8b8g8r8UintPack32 = 55,
        FormatA8b8g8r8SintPack32 = 56,
        FormatA8b8g8r8SrgbPack32 = 57,
        FormatA2r10g10b10UnormPack32 = 58,
        FormatA2r10g10b10SnormPack32 = 59,
        FormatA2r10g10b10UscaledPack32 = 60,
        FormatA2r10g10b10SscaledPack32 = 61,
        FormatA2r10g10b10UintPack32 = 62,
        FormatA2r10g10b10SintPack32 = 63,
        FormatA2b10g10r10UnormPack32 = 64,
        FormatA2b10g10r10SnormPack32 = 65,
        FormatA2b10g10r10UscaledPack32 = 66,
        FormatA2b10g10r10SscaledPack32 = 67,
        FormatA2b10g10r10UintPack32 = 68,
        FormatA2b10g10r10SintPack32 = 69,
        FormatR16Unorm = 70,
        FormatR16Snorm = 71,
        FormatR16Uscaled = 72,
        FormatR16Sscaled = 73,
        FormatR16Uint = 74,
        FormatR16Sint = 75,
        FormatR16Sfloat = 76,
        FormatR16g16Unorm = 77,
        FormatR16g16Snorm = 78,
        FormatR16g16Uscaled = 79,
        FormatR16g16Sscaled = 80,
        FormatR16g16Uint = 81,
        FormatR16g16Sint = 82,
        FormatR16g16Sfloat = 83,
        FormatR16g16b16Unorm = 84,
        FormatR16g16b16Snorm = 85,
        FormatR16g16b16Uscaled = 86,
        FormatR16g16b16Sscaled = 87,
        FormatR16g16b16Uint = 88,
        FormatR16g16b16Sint = 89,
        FormatR16g16b16Sfloat = 90,
        FormatR16g16b16a16Unorm = 91,
        FormatR16g16b16a16Snorm = 92,
        FormatR16g16b16a16Uscaled = 93,
        FormatR16g16b16a16Sscaled = 94,
        FormatR16g16b16a16Uint = 95,
        FormatR16g16b16a16Sint = 96,
        FormatR16g16b16a16Sfloat = 97,
        FormatR32Uint = 98,
        FormatR32Sint = 99,
        FormatR32Sfloat = 100,
        FormatR32g32Uint = 101,
        FormatR32g32Sint = 102,
        FormatR32g32Sfloat = 103,
        FormatR32g32b32Uint = 104,
        FormatR32g32b32Sint = 105,
        FormatR32g32b32Sfloat = 106,
        FormatR32g32b32a32Uint = 107,
        FormatR32g32b32a32Sint = 108,
        FormatR32g32b32a32Sfloat = 109,
        FormatR64Uint = 110,
        FormatR64Sint = 111,
        FormatR64Sfloat = 112,
        FormatR64g64Uint = 113,
        FormatR64g64Sint = 114,
        FormatR64g64Sfloat = 115,
        FormatR64g64b64Uint = 116,
        FormatR64g64b64Sint = 117,
        FormatR64g64b64Sfloat = 118,
        FormatR64g64b64a64Uint = 119,
        FormatR64g64b64a64Sint = 120,
        FormatR64g64b64a64Sfloat = 121,
        FormatB10g11r11UfloatPack32 = 122,
        FormatE5b9g9r9UfloatPack32 = 123,
        FormatD16Unorm = 124,
        FormatX8D24UnormPack32 = 125,
        FormatD32Sfloat = 126,
        FormatS8Uint = 127,
        FormatD16UnormS8Uint = 128,
        FormatD24UnormS8Uint = 129,
        FormatD32SfloatS8Uint = 130,
        FormatBc1RgbUnormBlock = 131,
        FormatBc1RgbSrgbBlock = 132,
        FormatBc1RgbaUnormBlock = 133,
        FormatBc1RgbaSrgbBlock = 134,
        FormatBc2UnormBlock = 135,
        FormatBc2SrgbBlock = 136,
        FormatBc3UnormBlock = 137,
        FormatBc3SrgbBlock = 138,
        FormatBc4UnormBlock = 139,
        FormatBc4SnormBlock = 140,
        FormatBc5UnormBlock = 141,
        FormatBc5SnormBlock = 142,
        FormatBc6hUfloatBlock = 143,
        FormatBc6hSfloatBlock = 144,
        FormatBc7UnormBlock = 145,
        FormatBc7SrgbBlock = 146,
        FormatEtc2R8g8b8UnormBlock = 147,
        FormatEtc2R8g8b8SrgbBlock = 148,
        FormatEtc2R8g8b8a1UnormBlock = 149,
        FormatEtc2R8g8b8a1SrgbBlock = 150,
        FormatEtc2R8g8b8a8UnormBlock = 151,
        FormatEtc2R8g8b8a8SrgbBlock = 152,
        FormatEacR11UnormBlock = 153,
        FormatEacR11SnormBlock = 154,
        FormatEacR11g11UnormBlock = 155,
        FormatEacR11g11SnormBlock = 156,
        FormatAstc4x4UnormBlock = 157,
        FormatAstc4x4SrgbBlock = 158,
        FormatAstc5x4UnormBlock = 159,
        FormatAstc5x4SrgbBlock = 160,
        FormatAstc5x5UnormBlock = 161,
        FormatAstc5x5SrgbBlock = 162,
        FormatAstc6x5UnormBlock = 163,
        FormatAstc6x5SrgbBlock = 164,
        FormatAstc6x6UnormBlock = 165,
        FormatAstc6x6SrgbBlock = 166,
        FormatAstc8x5UnormBlock = 167,
        FormatAstc8x5SrgbBlock = 168,
        FormatAstc8x6UnormBlock = 169,
        FormatAstc8x6SrgbBlock = 170,
        FormatAstc8x8UnormBlock = 171,
        FormatAstc8x8SrgbBlock = 172,
        FormatAstc10x5UnormBlock = 173,
        FormatAstc10x5SrgbBlock = 174,
        FormatAstc10x6UnormBlock = 175,
        FormatAstc10x6SrgbBlock = 176,
        FormatAstc10x8UnormBlock = 177,
        FormatAstc10x8SrgbBlock = 178,
        FormatAstc10x10UnormBlock = 179,
        FormatAstc10x10SrgbBlock = 180,
        FormatAstc12x10UnormBlock = 181,
        FormatAstc12x10SrgbBlock = 182,
        FormatAstc12x12UnormBlock = 183,
        FormatAstc12x12SrgbBlock = 184,
    }

    public enum VkFrontFace {
        FrontFaceCounterClockwise = 0,
        FrontFaceClockwise = 1,
    }

    public enum VkImageLayout {
        ImageLayoutUndefined = 0,
        ImageLayoutGeneral = 1,
        ImageLayoutColorAttachmentOptimal = 2,
        ImageLayoutDepthStencilAttachmentOptimal = 3,
        ImageLayoutDepthStencilReadOnlyOptimal = 4,
        ImageLayoutShaderReadOnlyOptimal = 5,
        ImageLayoutTransferSrcOptimal = 6,
        ImageLayoutTransferDstOptimal = 7,
        ImageLayoutPreinitialized = 8,
        ImageLayoutPresentSrcKhr = 1000001002,
    }

    public enum VkImageTiling {
        ImageTilingOptimal = 0,
        ImageTilingLinear = 1,
    }

    public enum VkImageType {
        ImageType1d = 0,
        ImageType2d = 1,
        ImageType3d = 2,
    }

    public enum VkImageViewType {
        ImageViewType1d = 0,
        ImageViewType2d = 1,
        ImageViewType3d = 2,
        ImageViewTypeCube = 3,
        ImageViewType1dArray = 4,
        ImageViewType2dArray = 5,
        ImageViewTypeCubeArray = 6,
    }

    public enum VkSharingMode {
        SharingModeExclusive = 0,
        SharingModeConcurrent = 1,
    }

    public enum VkIndexType {
        IndexTypeUint16 = 0,
        IndexTypeUint32 = 1,
    }

    public enum VkLogicOp {
        LogicOpClear = 0,
        LogicOpAnd = 1,
        LogicOpAndReverse = 2,
        LogicOpCopy = 3,
        LogicOpAndInverted = 4,
        LogicOpNoOp = 5,
        LogicOpXor = 6,
        LogicOpOr = 7,
        LogicOpNor = 8,
        LogicOpEquivalent = 9,
        LogicOpInvert = 10,
        LogicOpOrReverse = 11,
        LogicOpCopyInverted = 12,
        LogicOpOrInverted = 13,
        LogicOpNand = 14,
        LogicOpSet = 15,
    }

    public enum VkPhysicalDeviceType {
        PhysicalDeviceTypeOther = 0,
        PhysicalDeviceTypeIntegratedGpu = 1,
        PhysicalDeviceTypeDiscreteGpu = 2,
        PhysicalDeviceTypeVirtualGpu = 3,
        PhysicalDeviceTypeCpu = 4,
    }

    public enum VkPipelineBindPoint {
        PipelineBindPointGraphics = 0,
        PipelineBindPointCompute = 1,
    }

    public enum VkPrimitiveTopology {
        PrimitiveTopologyPointList = 0,
        PrimitiveTopologyLineList = 1,
        PrimitiveTopologyLineStrip = 2,
        PrimitiveTopologyTriangleList = 3,
        PrimitiveTopologyTriangleStrip = 4,
        PrimitiveTopologyTriangleFan = 5,
        PrimitiveTopologyLineListWithAdjacency = 6,
        PrimitiveTopologyLineStripWithAdjacency = 7,
        PrimitiveTopologyTriangleListWithAdjacency = 8,
        PrimitiveTopologyTriangleStripWithAdjacency = 9,
        PrimitiveTopologyPatchList = 10,
    }

    public enum VkQueryType {
        QueryTypeOcclusion = 0,
        QueryTypePipelineStatistics = 1,
        QueryTypeTimestamp = 2,
    }

    public enum VkSubpassContents {
        SubpassContentsInline = 0,
        SubpassContentsSecondaryCommandBuffers = 1,
    }

    public enum VkResult {
        Success = 0,
        NotReady = 1,
        Timeout = 2,
        EventSet = 3,
        EventReset = 4,
        Incomplete = 5,
        ErrorOutOfHostMemory = -1,
        ErrorOutOfDeviceMemory = -2,
        ErrorInitializationFailed = -3,
        ErrorDeviceLost = -4,
        ErrorMemoryMapFailed = -5,
        ErrorLayerNotPresent = -6,
        ErrorExtensionNotPresent = -7,
        ErrorFeatureNotPresent = -8,
        ErrorIncompatibleDriver = -9,
        ErrorTooManyObjects = -10,
        ErrorFormatNotSupported = -11,
        ErrorFragmentedPool = -12,
        ErrorSurfaceLostKhr = -1000000000,
        ErrorNativeWindowInUseKhr = -1000000001,
        SuboptimalKhr = 1000001003,
        ErrorOutOfDateKhr = -1000001004,
        ErrorIncompatibleDisplayKhr = -1000003001,
        ErrorValidationFailedExt = -1000011001,
    }

    public enum VkStencilOp {
        StencilOpKeep = 0,
        StencilOpZero = 1,
        StencilOpReplace = 2,
        StencilOpIncrementAndClamp = 3,
        StencilOpDecrementAndClamp = 4,
        StencilOpInvert = 5,
        StencilOpIncrementAndWrap = 6,
        StencilOpDecrementAndWrap = 7,
    }

    public enum VkStructureType {
        StructureTypeApplicationInfo = 0,
        StructureTypeInstanceCreateInfo = 1,
        StructureTypeDeviceQueueCreateInfo = 2,
        StructureTypeDeviceCreateInfo = 3,
        StructureTypeSubmitInfo = 4,
        StructureTypeMemoryAllocateInfo = 5,
        StructureTypeMappedMemoryRange = 6,
        StructureTypeBindSparseInfo = 7,
        StructureTypeFenceCreateInfo = 8,
        StructureTypeSemaphoreCreateInfo = 9,
        StructureTypeEventCreateInfo = 10,
        StructureTypeQueryPoolCreateInfo = 11,
        StructureTypeBufferCreateInfo = 12,
        StructureTypeBufferViewCreateInfo = 13,
        StructureTypeImageCreateInfo = 14,
        StructureTypeImageViewCreateInfo = 15,
        StructureTypeShaderModuleCreateInfo = 16,
        StructureTypePipelineCacheCreateInfo = 17,
        StructureTypePipelineShaderStageCreateInfo = 18,
        StructureTypePipelineVertexInputStateCreateInfo = 19,
        StructureTypePipelineInputAssemblyStateCreateInfo = 20,
        StructureTypePipelineTessellationStateCreateInfo = 21,
        StructureTypePipelineViewportStateCreateInfo = 22,
        StructureTypePipelineRasterizationStateCreateInfo = 23,
        StructureTypePipelineMultisampleStateCreateInfo = 24,
        StructureTypePipelineDepthStencilStateCreateInfo = 25,
        StructureTypePipelineColorBlendStateCreateInfo = 26,
        StructureTypePipelineDynamicStateCreateInfo = 27,
        StructureTypeGraphicsPipelineCreateInfo = 28,
        StructureTypeComputePipelineCreateInfo = 29,
        StructureTypePipelineLayoutCreateInfo = 30,
        StructureTypeSamplerCreateInfo = 31,
        StructureTypeDescriptorSetLayoutCreateInfo = 32,
        StructureTypeDescriptorPoolCreateInfo = 33,
        StructureTypeDescriptorSetAllocateInfo = 34,
        StructureTypeWriteDescriptorSet = 35,
        StructureTypeCopyDescriptorSet = 36,
        StructureTypeFramebufferCreateInfo = 37,
        StructureTypeRenderPassCreateInfo = 38,
        StructureTypeCommandPoolCreateInfo = 39,
        StructureTypeCommandBufferAllocateInfo = 40,
        StructureTypeCommandBufferInheritanceInfo = 41,
        StructureTypeCommandBufferBeginInfo = 42,
        StructureTypeRenderPassBeginInfo = 43,
        StructureTypeBufferMemoryBarrier = 44,
        StructureTypeImageMemoryBarrier = 45,
        StructureTypeMemoryBarrier = 46,
        StructureTypeLoaderInstanceCreateInfo = 47,
        StructureTypeLoaderDeviceCreateInfo = 48,
        StructureTypeSwapchainCreateInfoKhr = 1000001000,
        StructureTypePresentInfoKhr = 1000001001,
        StructureTypeDisplayModeCreateInfoKhr = 1000002000,
        StructureTypeDisplaySurfaceCreateInfoKhr = 1000002001,
        StructureTypeDisplayPresentInfoKhr = 1000003000,
        StructureTypeDebugReportCallbackCreateInfoExt = 1000011000,
    }

    public enum VkSystemAllocationScope {
        SystemAllocationScopeCommand = 0,
        SystemAllocationScopeObject = 1,
        SystemAllocationScopeCache = 2,
        SystemAllocationScopeDevice = 3,
        SystemAllocationScopeInstance = 4,
    }

    public enum VkInternalAllocationType {
        InternalAllocationTypeExecutable = 0,
    }

    public enum VkSamplerAddressMode {
        SamplerAddressModeRepeat = 0,
        SamplerAddressModeMirroredRepeat = 1,
        SamplerAddressModeClampToEdge = 2,
        SamplerAddressModeClampToBorder = 3,
    }

    public enum VkFilter {
        FilterNearest = 0,
        FilterLinear = 1,
    }

    public enum VkSamplerMipmapMode {
        SamplerMipmapModeNearest = 0,
        SamplerMipmapModeLinear = 1,
    }

    public enum VkVertexInputRate {
        VertexInputRateVertex = 0,
        VertexInputRateInstance = 1,
    }

    public enum VkColorSpaceKHR {
        ColorSpaceSrgbNonlinearKhr = 0,
    }

    public enum VkPresentModeKHR {
        PresentModeImmediateKhr = 0,
        PresentModeMailboxKhr = 1,
        PresentModeFifoKhr = 2,
        PresentModeFifoRelaxedKhr = 3,
    }

    public enum VkDebugReportObjectTypeEXT {
        DebugReportObjectTypeUnknownExt = 0,
        DebugReportObjectTypeInstanceExt = 1,
        DebugReportObjectTypePhysicalDeviceExt = 2,
        DebugReportObjectTypeDeviceExt = 3,
        DebugReportObjectTypeQueueExt = 4,
        DebugReportObjectTypeSemaphoreExt = 5,
        DebugReportObjectTypeCommandBufferExt = 6,
        DebugReportObjectTypeFenceExt = 7,
        DebugReportObjectTypeDeviceMemoryExt = 8,
        DebugReportObjectTypeBufferExt = 9,
        DebugReportObjectTypeImageExt = 10,
        DebugReportObjectTypeEventExt = 11,
        DebugReportObjectTypeQueryPoolExt = 12,
        DebugReportObjectTypeBufferViewExt = 13,
        DebugReportObjectTypeImageViewExt = 14,
        DebugReportObjectTypeShaderModuleExt = 15,
        DebugReportObjectTypePipelineCacheExt = 16,
        DebugReportObjectTypePipelineLayoutExt = 17,
        DebugReportObjectTypeRenderPassExt = 18,
        DebugReportObjectTypePipelineExt = 19,
        DebugReportObjectTypeDescriptorSetLayoutExt = 20,
        DebugReportObjectTypeSamplerExt = 21,
        DebugReportObjectTypeDescriptorPoolExt = 22,
        DebugReportObjectTypeDescriptorSetExt = 23,
        DebugReportObjectTypeFramebufferExt = 24,
        DebugReportObjectTypeCommandPoolExt = 25,
        DebugReportObjectTypeSurfaceKhrExt = 26,
        DebugReportObjectTypeSwapchainKhrExt = 27,
        DebugReportObjectTypeDebugReportExt = 28,
    }

    public enum VkDebugReportErrorEXT {
        DebugReportErrorNoneExt = 0,
        DebugReportErrorCallbackRefExt = 1,
    }

    public enum VkRasterizationOrderAMD {
        RasterizationOrderStrictAmd = 0,
        RasterizationOrderRelaxedAmd = 1,
    }

}
