//autogenerated on 9/19/2016 4:22:50 PM
using System;
using System.Runtime.InteropServices;

namespace CSGL.Vulkan {
    public struct VkInstance : IEquatable<VkInstance> {
        public IntPtr native;

        public static VkInstance Null { get; } = new VkInstance();

        public override bool Equals(object other) {
            if (other is VkInstance) {
                return Equals((VkInstance)other);
            }
            return false;
        }

        public bool Equals(VkInstance other) {
            return other.native == native;
        }

        public static bool operator == (VkInstance a, VkInstance b) {
            return a.Equals(b);
        }

        public static bool operator != (VkInstance a, VkInstance b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkPhysicalDevice : IEquatable<VkPhysicalDevice> {
        public IntPtr native;

        public static VkPhysicalDevice Null { get; } = new VkPhysicalDevice();

        public override bool Equals(object other) {
            if (other is VkPhysicalDevice) {
                return Equals((VkPhysicalDevice)other);
            }
            return false;
        }

        public bool Equals(VkPhysicalDevice other) {
            return other.native == native;
        }

        public static bool operator == (VkPhysicalDevice a, VkPhysicalDevice b) {
            return a.Equals(b);
        }

        public static bool operator != (VkPhysicalDevice a, VkPhysicalDevice b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDevice : IEquatable<VkDevice> {
        public IntPtr native;

        public static VkDevice Null { get; } = new VkDevice();

        public override bool Equals(object other) {
            if (other is VkDevice) {
                return Equals((VkDevice)other);
            }
            return false;
        }

        public bool Equals(VkDevice other) {
            return other.native == native;
        }

        public static bool operator == (VkDevice a, VkDevice b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDevice a, VkDevice b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkQueue : IEquatable<VkQueue> {
        public IntPtr native;

        public static VkQueue Null { get; } = new VkQueue();

        public override bool Equals(object other) {
            if (other is VkQueue) {
                return Equals((VkQueue)other);
            }
            return false;
        }

        public bool Equals(VkQueue other) {
            return other.native == native;
        }

        public static bool operator == (VkQueue a, VkQueue b) {
            return a.Equals(b);
        }

        public static bool operator != (VkQueue a, VkQueue b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkCommandBuffer : IEquatable<VkCommandBuffer> {
        public IntPtr native;

        public static VkCommandBuffer Null { get; } = new VkCommandBuffer();

        public override bool Equals(object other) {
            if (other is VkCommandBuffer) {
                return Equals((VkCommandBuffer)other);
            }
            return false;
        }

        public bool Equals(VkCommandBuffer other) {
            return other.native == native;
        }

        public static bool operator == (VkCommandBuffer a, VkCommandBuffer b) {
            return a.Equals(b);
        }

        public static bool operator != (VkCommandBuffer a, VkCommandBuffer b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDeviceMemory : IEquatable<VkDeviceMemory> {
        public ulong native;

        public static VkDeviceMemory Null { get; } = new VkDeviceMemory();

        public override bool Equals(object other) {
            if (other is VkDeviceMemory) {
                return Equals((VkDeviceMemory)other);
            }
            return false;
        }

        public bool Equals(VkDeviceMemory other) {
            return other.native == native;
        }

        public static bool operator == (VkDeviceMemory a, VkDeviceMemory b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDeviceMemory a, VkDeviceMemory b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkCommandPool : IEquatable<VkCommandPool> {
        public ulong native;

        public static VkCommandPool Null { get; } = new VkCommandPool();

        public override bool Equals(object other) {
            if (other is VkCommandPool) {
                return Equals((VkCommandPool)other);
            }
            return false;
        }

        public bool Equals(VkCommandPool other) {
            return other.native == native;
        }

        public static bool operator == (VkCommandPool a, VkCommandPool b) {
            return a.Equals(b);
        }

        public static bool operator != (VkCommandPool a, VkCommandPool b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkBuffer : IEquatable<VkBuffer> {
        public ulong native;

        public static VkBuffer Null { get; } = new VkBuffer();

        public override bool Equals(object other) {
            if (other is VkBuffer) {
                return Equals((VkBuffer)other);
            }
            return false;
        }

        public bool Equals(VkBuffer other) {
            return other.native == native;
        }

        public static bool operator == (VkBuffer a, VkBuffer b) {
            return a.Equals(b);
        }

        public static bool operator != (VkBuffer a, VkBuffer b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkBufferView : IEquatable<VkBufferView> {
        public ulong native;

        public static VkBufferView Null { get; } = new VkBufferView();

        public override bool Equals(object other) {
            if (other is VkBufferView) {
                return Equals((VkBufferView)other);
            }
            return false;
        }

        public bool Equals(VkBufferView other) {
            return other.native == native;
        }

        public static bool operator == (VkBufferView a, VkBufferView b) {
            return a.Equals(b);
        }

        public static bool operator != (VkBufferView a, VkBufferView b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkImage : IEquatable<VkImage> {
        public ulong native;

        public static VkImage Null { get; } = new VkImage();

        public override bool Equals(object other) {
            if (other is VkImage) {
                return Equals((VkImage)other);
            }
            return false;
        }

        public bool Equals(VkImage other) {
            return other.native == native;
        }

        public static bool operator == (VkImage a, VkImage b) {
            return a.Equals(b);
        }

        public static bool operator != (VkImage a, VkImage b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkImageView : IEquatable<VkImageView> {
        public ulong native;

        public static VkImageView Null { get; } = new VkImageView();

        public override bool Equals(object other) {
            if (other is VkImageView) {
                return Equals((VkImageView)other);
            }
            return false;
        }

        public bool Equals(VkImageView other) {
            return other.native == native;
        }

        public static bool operator == (VkImageView a, VkImageView b) {
            return a.Equals(b);
        }

        public static bool operator != (VkImageView a, VkImageView b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkShaderModule : IEquatable<VkShaderModule> {
        public ulong native;

        public static VkShaderModule Null { get; } = new VkShaderModule();

        public override bool Equals(object other) {
            if (other is VkShaderModule) {
                return Equals((VkShaderModule)other);
            }
            return false;
        }

        public bool Equals(VkShaderModule other) {
            return other.native == native;
        }

        public static bool operator == (VkShaderModule a, VkShaderModule b) {
            return a.Equals(b);
        }

        public static bool operator != (VkShaderModule a, VkShaderModule b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkPipeline : IEquatable<VkPipeline> {
        public ulong native;

        public static VkPipeline Null { get; } = new VkPipeline();

        public override bool Equals(object other) {
            if (other is VkPipeline) {
                return Equals((VkPipeline)other);
            }
            return false;
        }

        public bool Equals(VkPipeline other) {
            return other.native == native;
        }

        public static bool operator == (VkPipeline a, VkPipeline b) {
            return a.Equals(b);
        }

        public static bool operator != (VkPipeline a, VkPipeline b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkPipelineLayout : IEquatable<VkPipelineLayout> {
        public ulong native;

        public static VkPipelineLayout Null { get; } = new VkPipelineLayout();

        public override bool Equals(object other) {
            if (other is VkPipelineLayout) {
                return Equals((VkPipelineLayout)other);
            }
            return false;
        }

        public bool Equals(VkPipelineLayout other) {
            return other.native == native;
        }

        public static bool operator == (VkPipelineLayout a, VkPipelineLayout b) {
            return a.Equals(b);
        }

        public static bool operator != (VkPipelineLayout a, VkPipelineLayout b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkSampler : IEquatable<VkSampler> {
        public ulong native;

        public static VkSampler Null { get; } = new VkSampler();

        public override bool Equals(object other) {
            if (other is VkSampler) {
                return Equals((VkSampler)other);
            }
            return false;
        }

        public bool Equals(VkSampler other) {
            return other.native == native;
        }

        public static bool operator == (VkSampler a, VkSampler b) {
            return a.Equals(b);
        }

        public static bool operator != (VkSampler a, VkSampler b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDescriptorSet : IEquatable<VkDescriptorSet> {
        public ulong native;

        public static VkDescriptorSet Null { get; } = new VkDescriptorSet();

        public override bool Equals(object other) {
            if (other is VkDescriptorSet) {
                return Equals((VkDescriptorSet)other);
            }
            return false;
        }

        public bool Equals(VkDescriptorSet other) {
            return other.native == native;
        }

        public static bool operator == (VkDescriptorSet a, VkDescriptorSet b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDescriptorSet a, VkDescriptorSet b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDescriptorSetLayout : IEquatable<VkDescriptorSetLayout> {
        public ulong native;

        public static VkDescriptorSetLayout Null { get; } = new VkDescriptorSetLayout();

        public override bool Equals(object other) {
            if (other is VkDescriptorSetLayout) {
                return Equals((VkDescriptorSetLayout)other);
            }
            return false;
        }

        public bool Equals(VkDescriptorSetLayout other) {
            return other.native == native;
        }

        public static bool operator == (VkDescriptorSetLayout a, VkDescriptorSetLayout b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDescriptorSetLayout a, VkDescriptorSetLayout b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDescriptorPool : IEquatable<VkDescriptorPool> {
        public ulong native;

        public static VkDescriptorPool Null { get; } = new VkDescriptorPool();

        public override bool Equals(object other) {
            if (other is VkDescriptorPool) {
                return Equals((VkDescriptorPool)other);
            }
            return false;
        }

        public bool Equals(VkDescriptorPool other) {
            return other.native == native;
        }

        public static bool operator == (VkDescriptorPool a, VkDescriptorPool b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDescriptorPool a, VkDescriptorPool b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkFence : IEquatable<VkFence> {
        public ulong native;

        public static VkFence Null { get; } = new VkFence();

        public override bool Equals(object other) {
            if (other is VkFence) {
                return Equals((VkFence)other);
            }
            return false;
        }

        public bool Equals(VkFence other) {
            return other.native == native;
        }

        public static bool operator == (VkFence a, VkFence b) {
            return a.Equals(b);
        }

        public static bool operator != (VkFence a, VkFence b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkSemaphore : IEquatable<VkSemaphore> {
        public ulong native;

        public static VkSemaphore Null { get; } = new VkSemaphore();

        public override bool Equals(object other) {
            if (other is VkSemaphore) {
                return Equals((VkSemaphore)other);
            }
            return false;
        }

        public bool Equals(VkSemaphore other) {
            return other.native == native;
        }

        public static bool operator == (VkSemaphore a, VkSemaphore b) {
            return a.Equals(b);
        }

        public static bool operator != (VkSemaphore a, VkSemaphore b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkEvent : IEquatable<VkEvent> {
        public ulong native;

        public static VkEvent Null { get; } = new VkEvent();

        public override bool Equals(object other) {
            if (other is VkEvent) {
                return Equals((VkEvent)other);
            }
            return false;
        }

        public bool Equals(VkEvent other) {
            return other.native == native;
        }

        public static bool operator == (VkEvent a, VkEvent b) {
            return a.Equals(b);
        }

        public static bool operator != (VkEvent a, VkEvent b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkQueryPool : IEquatable<VkQueryPool> {
        public ulong native;

        public static VkQueryPool Null { get; } = new VkQueryPool();

        public override bool Equals(object other) {
            if (other is VkQueryPool) {
                return Equals((VkQueryPool)other);
            }
            return false;
        }

        public bool Equals(VkQueryPool other) {
            return other.native == native;
        }

        public static bool operator == (VkQueryPool a, VkQueryPool b) {
            return a.Equals(b);
        }

        public static bool operator != (VkQueryPool a, VkQueryPool b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkFramebuffer : IEquatable<VkFramebuffer> {
        public ulong native;

        public static VkFramebuffer Null { get; } = new VkFramebuffer();

        public override bool Equals(object other) {
            if (other is VkFramebuffer) {
                return Equals((VkFramebuffer)other);
            }
            return false;
        }

        public bool Equals(VkFramebuffer other) {
            return other.native == native;
        }

        public static bool operator == (VkFramebuffer a, VkFramebuffer b) {
            return a.Equals(b);
        }

        public static bool operator != (VkFramebuffer a, VkFramebuffer b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkRenderPass : IEquatable<VkRenderPass> {
        public ulong native;

        public static VkRenderPass Null { get; } = new VkRenderPass();

        public override bool Equals(object other) {
            if (other is VkRenderPass) {
                return Equals((VkRenderPass)other);
            }
            return false;
        }

        public bool Equals(VkRenderPass other) {
            return other.native == native;
        }

        public static bool operator == (VkRenderPass a, VkRenderPass b) {
            return a.Equals(b);
        }

        public static bool operator != (VkRenderPass a, VkRenderPass b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkPipelineCache : IEquatable<VkPipelineCache> {
        public ulong native;

        public static VkPipelineCache Null { get; } = new VkPipelineCache();

        public override bool Equals(object other) {
            if (other is VkPipelineCache) {
                return Equals((VkPipelineCache)other);
            }
            return false;
        }

        public bool Equals(VkPipelineCache other) {
            return other.native == native;
        }

        public static bool operator == (VkPipelineCache a, VkPipelineCache b) {
            return a.Equals(b);
        }

        public static bool operator != (VkPipelineCache a, VkPipelineCache b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDisplayKHR : IEquatable<VkDisplayKHR> {
        public ulong native;

        public static VkDisplayKHR Null { get; } = new VkDisplayKHR();

        public override bool Equals(object other) {
            if (other is VkDisplayKHR) {
                return Equals((VkDisplayKHR)other);
            }
            return false;
        }

        public bool Equals(VkDisplayKHR other) {
            return other.native == native;
        }

        public static bool operator == (VkDisplayKHR a, VkDisplayKHR b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDisplayKHR a, VkDisplayKHR b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDisplayModeKHR : IEquatable<VkDisplayModeKHR> {
        public ulong native;

        public static VkDisplayModeKHR Null { get; } = new VkDisplayModeKHR();

        public override bool Equals(object other) {
            if (other is VkDisplayModeKHR) {
                return Equals((VkDisplayModeKHR)other);
            }
            return false;
        }

        public bool Equals(VkDisplayModeKHR other) {
            return other.native == native;
        }

        public static bool operator == (VkDisplayModeKHR a, VkDisplayModeKHR b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDisplayModeKHR a, VkDisplayModeKHR b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkSurfaceKHR : IEquatable<VkSurfaceKHR> {
        public ulong native;

        public static VkSurfaceKHR Null { get; } = new VkSurfaceKHR();

        public override bool Equals(object other) {
            if (other is VkSurfaceKHR) {
                return Equals((VkSurfaceKHR)other);
            }
            return false;
        }

        public bool Equals(VkSurfaceKHR other) {
            return other.native == native;
        }

        public static bool operator == (VkSurfaceKHR a, VkSurfaceKHR b) {
            return a.Equals(b);
        }

        public static bool operator != (VkSurfaceKHR a, VkSurfaceKHR b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkSwapchainKHR : IEquatable<VkSwapchainKHR> {
        public ulong native;

        public static VkSwapchainKHR Null { get; } = new VkSwapchainKHR();

        public override bool Equals(object other) {
            if (other is VkSwapchainKHR) {
                return Equals((VkSwapchainKHR)other);
            }
            return false;
        }

        public bool Equals(VkSwapchainKHR other) {
            return other.native == native;
        }

        public static bool operator == (VkSwapchainKHR a, VkSwapchainKHR b) {
            return a.Equals(b);
        }

        public static bool operator != (VkSwapchainKHR a, VkSwapchainKHR b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    public struct VkDebugReportCallbackEXT : IEquatable<VkDebugReportCallbackEXT> {
        public ulong native;

        public static VkDebugReportCallbackEXT Null { get; } = new VkDebugReportCallbackEXT();

        public override bool Equals(object other) {
            if (other is VkDebugReportCallbackEXT) {
                return Equals((VkDebugReportCallbackEXT)other);
            }
            return false;
        }

        public bool Equals(VkDebugReportCallbackEXT other) {
            return other.native == native;
        }

        public static bool operator == (VkDebugReportCallbackEXT a, VkDebugReportCallbackEXT b) {
            return a.Equals(b);
        }

        public static bool operator != (VkDebugReportCallbackEXT a, VkDebugReportCallbackEXT b) {
            return !(a == b);
        }

        public override int GetHashCode() {
            return native.GetHashCode();
        }
    }

    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public struct VkOffset2D {
        [FieldOffset(0)]
        public int x;
        [FieldOffset(4)]
        public int y;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkOffset3D {
        [FieldOffset(0)]
        public int x;
        [FieldOffset(4)]
        public int y;
        [FieldOffset(8)]
        public int z;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public struct VkExtent2D {
        [FieldOffset(0)]
        public uint width;
        [FieldOffset(4)]
        public uint height;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkExtent3D {
        [FieldOffset(0)]
        public uint width;
        [FieldOffset(4)]
        public uint height;
        [FieldOffset(8)]
        public uint depth;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkViewport {
        [FieldOffset(0)]
        public float x;
        [FieldOffset(4)]
        public float y;
        [FieldOffset(8)]
        public float width;
        [FieldOffset(12)]
        public float height;
        [FieldOffset(16)]
        public float minDepth;
        [FieldOffset(20)]
        public float maxDepth;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkRect2D {
        [FieldOffset(0)]
        public VkOffset2D offset;
        [FieldOffset(8)]
        public VkExtent2D extent;
    }

    public struct VkRect3D {
        public VkOffset3D offset;
        public VkExtent3D extent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkClearRect {
        [FieldOffset(0)]
        public VkRect2D rect;
        [FieldOffset(16)]
        public uint baseArrayLayer;
        [FieldOffset(20)]
        public uint layerCount;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkComponentMapping {
        [FieldOffset(0)]
        public VkComponentSwizzle r;
        [FieldOffset(4)]
        public VkComponentSwizzle g;
        [FieldOffset(8)]
        public VkComponentSwizzle b;
        [FieldOffset(12)]
        public VkComponentSwizzle a;
    }

    [StructLayout(LayoutKind.Explicit, Size = 824)]
    public struct VkPhysicalDeviceProperties {
        [FieldOffset(0)]
        public uint apiVersion;
        [FieldOffset(4)]
        public uint driverVersion;
        [FieldOffset(8)]
        public uint vendorID;
        [FieldOffset(12)]
        public uint deviceID;
        [FieldOffset(16)]
        public VkPhysicalDeviceType deviceType;
        [FieldOffset(20)]
        public byte deviceName;
        [FieldOffset(276)]
        public byte pipelineCacheUUID;
        [FieldOffset(296)]
        public VkPhysicalDeviceLimits limits;
        [FieldOffset(800)]
        public VkPhysicalDeviceSparseProperties sparseProperties;
    }

    [StructLayout(LayoutKind.Explicit, Size = 260)]
    public struct VkExtensionProperties {
        [FieldOffset(0)]
        public byte extensionName;
        [FieldOffset(256)]
        public VkVersion specVersion;
    }

    [StructLayout(LayoutKind.Explicit, Size = 520)]
    public struct VkLayerProperties {
        [FieldOffset(0)]
        public byte layerName;
        [FieldOffset(256)]
        public VkVersion specVersion;
        [FieldOffset(260)]
        public uint implementationVersion;
        [FieldOffset(264)]
        public byte description;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkApplicationInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public IntPtr pApplicationName;
        [FieldOffset(24)]
        public VkVersion applicationVersion;
        [FieldOffset(32)]
        public IntPtr pEngineName;
        [FieldOffset(40)]
        public VkVersion engineVersion;
        [FieldOffset(44)]
        public VkVersion apiVersion;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkAllocationCallbacks {
        [FieldOffset(0)]
        public IntPtr pUserData;
        [FieldOffset(8)]
        public IntPtr pfnAllocation;
        [FieldOffset(16)]
        public IntPtr pfnReallocation;
        [FieldOffset(24)]
        public IntPtr pfnFree;
        [FieldOffset(32)]
        public IntPtr pfnInternalAllocation;
        [FieldOffset(40)]
        public IntPtr pfnInternalFree;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkDeviceQueueCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDeviceQueueCreateFlags flags;
        [FieldOffset(20)]
        public uint queueFamilyIndex;
        [FieldOffset(24)]
        public uint queueCount;
        [FieldOffset(32)]
        public IntPtr pQueuePriorities;
    }

    [StructLayout(LayoutKind.Explicit, Size = 72)]
    public struct VkDeviceCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDeviceCreateFlags flags;
        [FieldOffset(20)]
        public uint queueCreateInfoCount;
        [FieldOffset(24)]
        public IntPtr pQueueCreateInfos;
        [FieldOffset(32)]
        public uint enabledLayerCount;
        [FieldOffset(40)]
        public IntPtr ppEnabledLayerNames;
        [FieldOffset(48)]
        public uint enabledExtensionCount;
        [FieldOffset(56)]
        public IntPtr ppEnabledExtensionNames;
        [FieldOffset(64)]
        public IntPtr pEnabledFeatures;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkInstanceCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkInstanceCreateFlags flags;
        [FieldOffset(24)]
        public IntPtr pApplicationInfo;
        [FieldOffset(32)]
        public uint enabledLayerCount;
        [FieldOffset(40)]
        public IntPtr ppEnabledLayerNames;
        [FieldOffset(48)]
        public uint enabledExtensionCount;
        [FieldOffset(56)]
        public IntPtr ppEnabledExtensionNames;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkQueueFamilyProperties {
        [FieldOffset(0)]
        public VkQueueFlags queueFlags;
        [FieldOffset(4)]
        public uint queueCount;
        [FieldOffset(8)]
        public uint timestampValidBits;
        [FieldOffset(12)]
        public VkExtent3D minImageTransferGranularity;
    }

    [StructLayout(LayoutKind.Explicit, Size = 520)]
    public struct VkPhysicalDeviceMemoryProperties {
        [FieldOffset(0)]
        public uint memoryTypeCount;
        [FieldOffset(4)]
        public VkMemoryType memoryTypes;
        [FieldOffset(12)]
        public VkMemoryType memoryTypes1;
        [FieldOffset(20)]
        public VkMemoryType memoryTypes2;
        [FieldOffset(28)]
        public VkMemoryType memoryTypes3;
        [FieldOffset(36)]
        public VkMemoryType memoryTypes4;
        [FieldOffset(44)]
        public VkMemoryType memoryTypes5;
        [FieldOffset(52)]
        public VkMemoryType memoryTypes6;
        [FieldOffset(60)]
        public VkMemoryType memoryTypes7;
        [FieldOffset(68)]
        public VkMemoryType memoryTypes8;
        [FieldOffset(76)]
        public VkMemoryType memoryTypes9;
        [FieldOffset(84)]
        public VkMemoryType memoryTypes10;
        [FieldOffset(92)]
        public VkMemoryType memoryTypes11;
        [FieldOffset(100)]
        public VkMemoryType memoryTypes12;
        [FieldOffset(108)]
        public VkMemoryType memoryTypes13;
        [FieldOffset(116)]
        public VkMemoryType memoryTypes14;
        [FieldOffset(124)]
        public VkMemoryType memoryTypes15;
        [FieldOffset(132)]
        public VkMemoryType memoryTypes16;
        [FieldOffset(140)]
        public VkMemoryType memoryTypes17;
        [FieldOffset(148)]
        public VkMemoryType memoryTypes18;
        [FieldOffset(156)]
        public VkMemoryType memoryTypes19;
        [FieldOffset(164)]
        public VkMemoryType memoryTypes20;
        [FieldOffset(172)]
        public VkMemoryType memoryTypes21;
        [FieldOffset(180)]
        public VkMemoryType memoryTypes22;
        [FieldOffset(188)]
        public VkMemoryType memoryTypes23;
        [FieldOffset(196)]
        public VkMemoryType memoryTypes24;
        [FieldOffset(204)]
        public VkMemoryType memoryTypes25;
        [FieldOffset(212)]
        public VkMemoryType memoryTypes26;
        [FieldOffset(220)]
        public VkMemoryType memoryTypes27;
        [FieldOffset(228)]
        public VkMemoryType memoryTypes28;
        [FieldOffset(236)]
        public VkMemoryType memoryTypes29;
        [FieldOffset(244)]
        public VkMemoryType memoryTypes30;
        [FieldOffset(252)]
        public VkMemoryType memoryTypes31;
        [FieldOffset(260)]
        public uint memoryHeapCount;
        [FieldOffset(264)]
        public VkMemoryHeap memoryHeaps;
        [FieldOffset(280)]
        public VkMemoryHeap memoryHeaps1;
        [FieldOffset(296)]
        public VkMemoryHeap memoryHeaps2;
        [FieldOffset(312)]
        public VkMemoryHeap memoryHeaps3;
        [FieldOffset(328)]
        public VkMemoryHeap memoryHeaps4;
        [FieldOffset(344)]
        public VkMemoryHeap memoryHeaps5;
        [FieldOffset(360)]
        public VkMemoryHeap memoryHeaps6;
        [FieldOffset(376)]
        public VkMemoryHeap memoryHeaps7;
        [FieldOffset(392)]
        public VkMemoryHeap memoryHeaps8;
        [FieldOffset(408)]
        public VkMemoryHeap memoryHeaps9;
        [FieldOffset(424)]
        public VkMemoryHeap memoryHeaps10;
        [FieldOffset(440)]
        public VkMemoryHeap memoryHeaps11;
        [FieldOffset(456)]
        public VkMemoryHeap memoryHeaps12;
        [FieldOffset(472)]
        public VkMemoryHeap memoryHeaps13;
        [FieldOffset(488)]
        public VkMemoryHeap memoryHeaps14;
        [FieldOffset(504)]
        public VkMemoryHeap memoryHeaps15;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkMemoryAllocateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public ulong allocationSize;
        [FieldOffset(24)]
        public uint memoryTypeIndex;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkMemoryRequirements {
        [FieldOffset(0)]
        public ulong size;
        [FieldOffset(8)]
        public ulong alignment;
        [FieldOffset(16)]
        public uint memoryTypeBits;
    }

    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public struct VkSparseImageFormatProperties {
        [FieldOffset(0)]
        public VkImageAspectFlags aspectMask;
        [FieldOffset(4)]
        public VkExtent3D imageGranularity;
        [FieldOffset(16)]
        public VkSparseImageFormatFlags flags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkSparseImageMemoryRequirements {
        [FieldOffset(0)]
        public VkSparseImageFormatProperties formatProperties;
        [FieldOffset(20)]
        public uint imageMipTailFirstLod;
        [FieldOffset(24)]
        public ulong imageMipTailSize;
        [FieldOffset(32)]
        public ulong imageMipTailOffset;
        [FieldOffset(40)]
        public ulong imageMipTailStride;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public struct VkMemoryType {
        [FieldOffset(0)]
        public VkMemoryPropertyFlags propertyFlags;
        [FieldOffset(4)]
        public uint heapIndex;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkMemoryHeap {
        [FieldOffset(0)]
        public ulong size;
        [FieldOffset(8)]
        public VkMemoryHeapFlags flags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkMappedMemoryRange {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDeviceMemory memory;
        [FieldOffset(24)]
        public ulong offset;
        [FieldOffset(32)]
        public ulong size;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkFormatProperties {
        [FieldOffset(0)]
        public VkFormatFeatureFlags linearTilingFeatures;
        [FieldOffset(4)]
        public VkFormatFeatureFlags optimalTilingFeatures;
        [FieldOffset(8)]
        public VkFormatFeatureFlags bufferFeatures;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkImageFormatProperties {
        [FieldOffset(0)]
        public VkExtent3D maxExtent;
        [FieldOffset(12)]
        public uint maxMipLevels;
        [FieldOffset(16)]
        public uint maxArrayLayers;
        [FieldOffset(20)]
        public VkSampleCountFlags sampleCounts;
        [FieldOffset(24)]
        public ulong maxResourceSize;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkDescriptorBufferInfo {
        [FieldOffset(0)]
        public VkBuffer buffer;
        [FieldOffset(8)]
        public ulong offset;
        [FieldOffset(16)]
        public ulong range;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkDescriptorImageInfo {
        [FieldOffset(0)]
        public VkSampler sampler;
        [FieldOffset(8)]
        public VkImageView imageView;
        [FieldOffset(16)]
        public VkImageLayout imageLayout;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkWriteDescriptorSet {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDescriptorSet dstSet;
        [FieldOffset(24)]
        public uint dstBinding;
        [FieldOffset(28)]
        public uint dstArrayElement;
        [FieldOffset(32)]
        public uint descriptorCount;
        [FieldOffset(36)]
        public VkDescriptorType descriptorType;
        [FieldOffset(40)]
        public IntPtr pImageInfo;
        [FieldOffset(48)]
        public IntPtr pBufferInfo;
        [FieldOffset(56)]
        public IntPtr pTexelBufferView;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkCopyDescriptorSet {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDescriptorSet srcSet;
        [FieldOffset(24)]
        public uint srcBinding;
        [FieldOffset(28)]
        public uint srcArrayElement;
        [FieldOffset(32)]
        public VkDescriptorSet dstSet;
        [FieldOffset(40)]
        public uint dstBinding;
        [FieldOffset(44)]
        public uint dstArrayElement;
        [FieldOffset(48)]
        public uint descriptorCount;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkBufferCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkBufferCreateFlags flags;
        [FieldOffset(24)]
        public ulong size;
        [FieldOffset(32)]
        public VkBufferUsageFlags usage;
        [FieldOffset(36)]
        public VkSharingMode sharingMode;
        [FieldOffset(40)]
        public uint queueFamilyIndexCount;
        [FieldOffset(48)]
        public IntPtr pQueueFamilyIndices;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkBufferViewCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkBufferViewCreateFlags flags;
        [FieldOffset(24)]
        public VkBuffer buffer;
        [FieldOffset(32)]
        public VkFormat format;
        [FieldOffset(40)]
        public ulong offset;
        [FieldOffset(48)]
        public ulong range;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkImageSubresource {
        [FieldOffset(0)]
        public VkImageAspectFlags aspectMask;
        [FieldOffset(4)]
        public uint mipLevel;
        [FieldOffset(8)]
        public uint arrayLayer;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkImageSubresourceLayers {
        [FieldOffset(0)]
        public VkImageAspectFlags aspectMask;
        [FieldOffset(4)]
        public uint mipLevel;
        [FieldOffset(8)]
        public uint baseArrayLayer;
        [FieldOffset(12)]
        public uint layerCount;
    }

    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public struct VkImageSubresourceRange {
        [FieldOffset(0)]
        public VkImageAspectFlags aspectMask;
        [FieldOffset(4)]
        public uint baseMipLevel;
        [FieldOffset(8)]
        public uint levelCount;
        [FieldOffset(12)]
        public uint baseArrayLayer;
        [FieldOffset(16)]
        public uint layerCount;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkMemoryBarrier {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkAccessFlags srcAccessMask;
        [FieldOffset(20)]
        public VkAccessFlags dstAccessMask;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkBufferMemoryBarrier {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkAccessFlags srcAccessMask;
        [FieldOffset(20)]
        public VkAccessFlags dstAccessMask;
        [FieldOffset(24)]
        public uint srcQueueFamilyIndex;
        [FieldOffset(28)]
        public uint dstQueueFamilyIndex;
        [FieldOffset(32)]
        public VkBuffer buffer;
        [FieldOffset(40)]
        public ulong offset;
        [FieldOffset(48)]
        public ulong size;
    }

    [StructLayout(LayoutKind.Explicit, Size = 72)]
    public struct VkImageMemoryBarrier {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkAccessFlags srcAccessMask;
        [FieldOffset(20)]
        public VkAccessFlags dstAccessMask;
        [FieldOffset(24)]
        public VkImageLayout oldLayout;
        [FieldOffset(28)]
        public VkImageLayout newLayout;
        [FieldOffset(32)]
        public uint srcQueueFamilyIndex;
        [FieldOffset(36)]
        public uint dstQueueFamilyIndex;
        [FieldOffset(40)]
        public VkImage image;
        [FieldOffset(48)]
        public VkImageSubresourceRange subresourceRange;
    }

    [StructLayout(LayoutKind.Explicit, Size = 88)]
    public struct VkImageCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkImageCreateFlags flags;
        [FieldOffset(20)]
        public VkImageType imageType;
        [FieldOffset(24)]
        public VkFormat format;
        [FieldOffset(28)]
        public VkExtent3D extent;
        [FieldOffset(40)]
        public uint mipLevels;
        [FieldOffset(44)]
        public uint arrayLayers;
        [FieldOffset(48)]
        public VkSampleCountFlags samples;
        [FieldOffset(52)]
        public VkImageTiling tiling;
        [FieldOffset(56)]
        public VkImageUsageFlags usage;
        [FieldOffset(60)]
        public VkSharingMode sharingMode;
        [FieldOffset(64)]
        public uint queueFamilyIndexCount;
        [FieldOffset(72)]
        public IntPtr pQueueFamilyIndices;
        [FieldOffset(80)]
        public VkImageLayout initialLayout;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkSubresourceLayout {
        [FieldOffset(0)]
        public ulong offset;
        [FieldOffset(8)]
        public ulong size;
        [FieldOffset(16)]
        public ulong rowPitch;
        [FieldOffset(24)]
        public ulong arrayPitch;
        [FieldOffset(32)]
        public ulong depthPitch;
    }

    [StructLayout(LayoutKind.Explicit, Size = 80)]
    public struct VkImageViewCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkImageViewCreateFlags flags;
        [FieldOffset(24)]
        public VkImage image;
        [FieldOffset(32)]
        public VkImageViewType viewType;
        [FieldOffset(36)]
        public VkFormat format;
        [FieldOffset(40)]
        public VkComponentMapping components;
        [FieldOffset(56)]
        public VkImageSubresourceRange subresourceRange;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkBufferCopy {
        [FieldOffset(0)]
        public ulong srcOffset;
        [FieldOffset(8)]
        public ulong dstOffset;
        [FieldOffset(16)]
        public ulong size;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkSparseMemoryBind {
        [FieldOffset(0)]
        public ulong resourceOffset;
        [FieldOffset(8)]
        public ulong size;
        [FieldOffset(16)]
        public VkDeviceMemory memory;
        [FieldOffset(24)]
        public ulong memoryOffset;
        [FieldOffset(32)]
        public VkSparseMemoryBindFlags flags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkSparseImageMemoryBind {
        [FieldOffset(0)]
        public VkImageSubresource subresource;
        [FieldOffset(12)]
        public VkOffset3D offset;
        [FieldOffset(24)]
        public VkExtent3D extent;
        [FieldOffset(40)]
        public VkDeviceMemory memory;
        [FieldOffset(48)]
        public ulong memoryOffset;
        [FieldOffset(56)]
        public VkSparseMemoryBindFlags flags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkSparseBufferMemoryBindInfo {
        [FieldOffset(0)]
        public VkBuffer buffer;
        [FieldOffset(8)]
        public uint bindCount;
        [FieldOffset(16)]
        public IntPtr pBinds;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkSparseImageOpaqueMemoryBindInfo {
        [FieldOffset(0)]
        public VkImage image;
        [FieldOffset(8)]
        public uint bindCount;
        [FieldOffset(16)]
        public IntPtr pBinds;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkSparseImageMemoryBindInfo {
        [FieldOffset(0)]
        public VkImage image;
        [FieldOffset(8)]
        public uint bindCount;
        [FieldOffset(16)]
        public IntPtr pBinds;
    }

    [StructLayout(LayoutKind.Explicit, Size = 96)]
    public struct VkBindSparseInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public uint waitSemaphoreCount;
        [FieldOffset(24)]
        public IntPtr pWaitSemaphores;
        [FieldOffset(32)]
        public uint bufferBindCount;
        [FieldOffset(40)]
        public IntPtr pBufferBinds;
        [FieldOffset(48)]
        public uint imageOpaqueBindCount;
        [FieldOffset(56)]
        public IntPtr pImageOpaqueBinds;
        [FieldOffset(64)]
        public uint imageBindCount;
        [FieldOffset(72)]
        public IntPtr pImageBinds;
        [FieldOffset(80)]
        public uint signalSemaphoreCount;
        [FieldOffset(88)]
        public IntPtr pSignalSemaphores;
    }

    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public struct VkImageCopy {
        [FieldOffset(0)]
        public VkImageSubresourceLayers srcSubresource;
        [FieldOffset(16)]
        public VkOffset3D srcOffset;
        [FieldOffset(28)]
        public VkImageSubresourceLayers dstSubresource;
        [FieldOffset(44)]
        public VkOffset3D dstOffset;
        [FieldOffset(56)]
        public VkExtent3D extent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 80)]
    public struct VkImageBlit {
        [FieldOffset(0)]
        public VkImageSubresourceLayers srcSubresource;
        [FieldOffset(16)]
        public VkOffset3D srcOffsets;
        [FieldOffset(40)]
        public VkImageSubresourceLayers dstSubresource;
        [FieldOffset(56)]
        public VkOffset3D dstOffsets;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkBufferImageCopy {
        [FieldOffset(0)]
        public ulong bufferOffset;
        [FieldOffset(8)]
        public uint bufferRowLength;
        [FieldOffset(12)]
        public uint bufferImageHeight;
        [FieldOffset(16)]
        public VkImageSubresourceLayers imageSubresource;
        [FieldOffset(32)]
        public VkOffset3D imageOffset;
        [FieldOffset(44)]
        public VkExtent3D imageExtent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public struct VkImageResolve {
        [FieldOffset(0)]
        public VkImageSubresourceLayers srcSubresource;
        [FieldOffset(16)]
        public VkOffset3D srcOffset;
        [FieldOffset(28)]
        public VkImageSubresourceLayers dstSubresource;
        [FieldOffset(44)]
        public VkOffset3D dstOffset;
        [FieldOffset(56)]
        public VkExtent3D extent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkShaderModuleCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkShaderModuleCreateFlags flags;
        [FieldOffset(24)]
        public ulong codeSize;
        [FieldOffset(32)]
        public IntPtr pCode;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkDescriptorSetLayoutBinding {
        [FieldOffset(0)]
        public uint binding;
        [FieldOffset(4)]
        public VkDescriptorType descriptorType;
        [FieldOffset(8)]
        public uint descriptorCount;
        [FieldOffset(12)]
        public VkShaderStageFlags stageFlags;
        [FieldOffset(16)]
        public IntPtr pImmutableSamplers;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkDescriptorSetLayoutCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDescriptorSetLayoutCreateFlags flags;
        [FieldOffset(20)]
        public uint bindingCount;
        [FieldOffset(24)]
        public IntPtr pBindings;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public struct VkDescriptorPoolSize {
        [FieldOffset(0)]
        public VkDescriptorType type;
        [FieldOffset(4)]
        public uint descriptorCount;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkDescriptorPoolCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDescriptorPoolCreateFlags flags;
        [FieldOffset(20)]
        public uint maxSets;
        [FieldOffset(24)]
        public uint poolSizeCount;
        [FieldOffset(32)]
        public IntPtr pPoolSizes;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkDescriptorSetAllocateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDescriptorPool descriptorPool;
        [FieldOffset(24)]
        public uint descriptorSetCount;
        [FieldOffset(32)]
        public IntPtr pSetLayouts;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkSpecializationMapEntry {
        [FieldOffset(0)]
        public uint constantID;
        [FieldOffset(4)]
        public uint offset;
        [FieldOffset(8)]
        public ulong size;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkSpecializationInfo {
        [FieldOffset(0)]
        public uint mapEntryCount;
        [FieldOffset(8)]
        public IntPtr pMapEntries;
        [FieldOffset(16)]
        public ulong dataSize;
        [FieldOffset(24)]
        public IntPtr pData;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkPipelineShaderStageCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineShaderStageCreateFlags flags;
        [FieldOffset(20)]
        public VkShaderStageFlags stage;
        [FieldOffset(24)]
        public VkShaderModule module;
        [FieldOffset(32)]
        public IntPtr pName;
        [FieldOffset(40)]
        public IntPtr pSpecializationInfo;
    }

    [StructLayout(LayoutKind.Explicit, Size = 96)]
    public struct VkComputePipelineCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineCreateFlags flags;
        [FieldOffset(24)]
        public VkPipelineShaderStageCreateInfo stage;
        [FieldOffset(72)]
        public VkPipelineLayout layout;
        [FieldOffset(80)]
        public VkPipeline basePipelineHandle;
        [FieldOffset(88)]
        public int basePipelineIndex;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkVertexInputBindingDescription {
        [FieldOffset(0)]
        public uint binding;
        [FieldOffset(4)]
        public uint stride;
        [FieldOffset(8)]
        public VkVertexInputRate inputRate;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkVertexInputAttributeDescription {
        [FieldOffset(0)]
        public uint location;
        [FieldOffset(4)]
        public uint binding;
        [FieldOffset(8)]
        public VkFormat format;
        [FieldOffset(12)]
        public uint offset;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkPipelineVertexInputStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineVertexInputStateCreateFlags flags;
        [FieldOffset(20)]
        public uint vertexBindingDescriptionCount;
        [FieldOffset(24)]
        public IntPtr pVertexBindingDescriptions;
        [FieldOffset(32)]
        public uint vertexAttributeDescriptionCount;
        [FieldOffset(40)]
        public IntPtr pVertexAttributeDescriptions;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkPipelineInputAssemblyStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineInputAssemblyStateCreateFlags flags;
        [FieldOffset(20)]
        public VkPrimitiveTopology topology;
        [FieldOffset(24)]
        public uint primitiveRestartEnable;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkPipelineTessellationStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineTessellationStateCreateFlags flags;
        [FieldOffset(20)]
        public uint patchControlPoints;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkPipelineViewportStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineViewportStateCreateFlags flags;
        [FieldOffset(20)]
        public uint viewportCount;
        [FieldOffset(24)]
        public IntPtr pViewports;
        [FieldOffset(32)]
        public uint scissorCount;
        [FieldOffset(40)]
        public IntPtr pScissors;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkPipelineRasterizationStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineRasterizationStateCreateFlags flags;
        [FieldOffset(20)]
        public uint depthClampEnable;
        [FieldOffset(24)]
        public uint rasterizerDiscardEnable;
        [FieldOffset(28)]
        public VkPolygonMode polygonMode;
        [FieldOffset(32)]
        public VkCullModeFlags cullMode;
        [FieldOffset(36)]
        public VkFrontFace frontFace;
        [FieldOffset(40)]
        public uint depthBiasEnable;
        [FieldOffset(44)]
        public float depthBiasConstantFactor;
        [FieldOffset(48)]
        public float depthBiasClamp;
        [FieldOffset(52)]
        public float depthBiasSlopeFactor;
        [FieldOffset(56)]
        public float lineWidth;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkPipelineMultisampleStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineMultisampleStateCreateFlags flags;
        [FieldOffset(20)]
        public VkSampleCountFlags rasterizationSamples;
        [FieldOffset(24)]
        public uint sampleShadingEnable;
        [FieldOffset(28)]
        public float minSampleShading;
        [FieldOffset(32)]
        public IntPtr pSampleMask;
        [FieldOffset(40)]
        public uint alphaToCoverageEnable;
        [FieldOffset(44)]
        public uint alphaToOneEnable;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkPipelineColorBlendAttachmentState {
        [FieldOffset(0)]
        public uint blendEnable;
        [FieldOffset(4)]
        public VkBlendFactor srcColorBlendFactor;
        [FieldOffset(8)]
        public VkBlendFactor dstColorBlendFactor;
        [FieldOffset(12)]
        public VkBlendOp colorBlendOp;
        [FieldOffset(16)]
        public VkBlendFactor srcAlphaBlendFactor;
        [FieldOffset(20)]
        public VkBlendFactor dstAlphaBlendFactor;
        [FieldOffset(24)]
        public VkBlendOp alphaBlendOp;
        [FieldOffset(28)]
        public VkColorComponentFlags colorWriteMask;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkPipelineColorBlendStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineColorBlendStateCreateFlags flags;
        [FieldOffset(20)]
        public uint logicOpEnable;
        [FieldOffset(24)]
        public VkLogicOp logicOp;
        [FieldOffset(28)]
        public uint attachmentCount;
        [FieldOffset(32)]
        public IntPtr pAttachments;
        [FieldOffset(40)]
        public float blendConstants;
        [FieldOffset(44)]
        public float blendConstants1;
        [FieldOffset(48)]
        public float blendConstants2;
        [FieldOffset(52)]
        public float blendConstants3;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkPipelineDynamicStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineDynamicStateCreateFlags flags;
        [FieldOffset(20)]
        public uint dynamicStateCount;
        [FieldOffset(24)]
        public IntPtr pDynamicStates;
    }

    [StructLayout(LayoutKind.Explicit, Size = 28)]
    public struct VkStencilOpState {
        [FieldOffset(0)]
        public VkStencilOp failOp;
        [FieldOffset(4)]
        public VkStencilOp passOp;
        [FieldOffset(8)]
        public VkStencilOp depthFailOp;
        [FieldOffset(12)]
        public VkCompareOp compareOp;
        [FieldOffset(16)]
        public uint compareMask;
        [FieldOffset(20)]
        public uint writeMask;
        [FieldOffset(24)]
        public uint reference;
    }

    [StructLayout(LayoutKind.Explicit, Size = 104)]
    public struct VkPipelineDepthStencilStateCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineDepthStencilStateCreateFlags flags;
        [FieldOffset(20)]
        public uint depthTestEnable;
        [FieldOffset(24)]
        public uint depthWriteEnable;
        [FieldOffset(28)]
        public VkCompareOp depthCompareOp;
        [FieldOffset(32)]
        public uint depthBoundsTestEnable;
        [FieldOffset(36)]
        public uint stencilTestEnable;
        [FieldOffset(40)]
        public VkStencilOpState front;
        [FieldOffset(68)]
        public VkStencilOpState back;
        [FieldOffset(96)]
        public float minDepthBounds;
        [FieldOffset(100)]
        public float maxDepthBounds;
    }

    [StructLayout(LayoutKind.Explicit, Size = 144)]
    public struct VkGraphicsPipelineCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineCreateFlags flags;
        [FieldOffset(20)]
        public uint stageCount;
        [FieldOffset(24)]
        public IntPtr pStages;
        [FieldOffset(32)]
        public IntPtr pVertexInputState;
        [FieldOffset(40)]
        public IntPtr pInputAssemblyState;
        [FieldOffset(48)]
        public IntPtr pTessellationState;
        [FieldOffset(56)]
        public IntPtr pViewportState;
        [FieldOffset(64)]
        public IntPtr pRasterizationState;
        [FieldOffset(72)]
        public IntPtr pMultisampleState;
        [FieldOffset(80)]
        public IntPtr pDepthStencilState;
        [FieldOffset(88)]
        public IntPtr pColorBlendState;
        [FieldOffset(96)]
        public IntPtr pDynamicState;
        [FieldOffset(104)]
        public VkPipelineLayout layout;
        [FieldOffset(112)]
        public VkRenderPass renderPass;
        [FieldOffset(120)]
        public uint subpass;
        [FieldOffset(128)]
        public VkPipeline basePipelineHandle;
        [FieldOffset(136)]
        public int basePipelineIndex;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkPipelineCacheCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineCacheCreateFlags flags;
        [FieldOffset(24)]
        public ulong initialDataSize;
        [FieldOffset(32)]
        public IntPtr pInitialData;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkPushConstantRange {
        [FieldOffset(0)]
        public VkShaderStageFlags stageFlags;
        [FieldOffset(4)]
        public uint offset;
        [FieldOffset(8)]
        public uint size;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkPipelineLayoutCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkPipelineLayoutCreateFlags flags;
        [FieldOffset(20)]
        public uint setLayoutCount;
        [FieldOffset(24)]
        public IntPtr pSetLayouts;
        [FieldOffset(32)]
        public uint pushConstantRangeCount;
        [FieldOffset(40)]
        public IntPtr pPushConstantRanges;
    }

    [StructLayout(LayoutKind.Explicit, Size = 80)]
    public struct VkSamplerCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkSamplerCreateFlags flags;
        [FieldOffset(20)]
        public VkFilter magFilter;
        [FieldOffset(24)]
        public VkFilter minFilter;
        [FieldOffset(28)]
        public VkSamplerMipmapMode mipmapMode;
        [FieldOffset(32)]
        public VkSamplerAddressMode addressModeU;
        [FieldOffset(36)]
        public VkSamplerAddressMode addressModeV;
        [FieldOffset(40)]
        public VkSamplerAddressMode addressModeW;
        [FieldOffset(44)]
        public float mipLodBias;
        [FieldOffset(48)]
        public uint anisotropyEnable;
        [FieldOffset(52)]
        public float maxAnisotropy;
        [FieldOffset(56)]
        public uint compareEnable;
        [FieldOffset(60)]
        public VkCompareOp compareOp;
        [FieldOffset(64)]
        public float minLod;
        [FieldOffset(68)]
        public float maxLod;
        [FieldOffset(72)]
        public VkBorderColor borderColor;
        [FieldOffset(76)]
        public uint unnormalizedCoordinates;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkCommandPoolCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkCommandPoolCreateFlags flags;
        [FieldOffset(20)]
        public uint queueFamilyIndex;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkCommandBufferAllocateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkCommandPool commandPool;
        [FieldOffset(24)]
        public VkCommandBufferLevel level;
        [FieldOffset(28)]
        public uint commandBufferCount;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkCommandBufferInheritanceInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkRenderPass renderPass;
        [FieldOffset(24)]
        public uint subpass;
        [FieldOffset(32)]
        public VkFramebuffer framebuffer;
        [FieldOffset(40)]
        public uint occlusionQueryEnable;
        [FieldOffset(44)]
        public VkQueryControlFlags queryFlags;
        [FieldOffset(48)]
        public VkQueryPipelineStatisticFlags pipelineStatistics;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkCommandBufferBeginInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkCommandBufferUsageFlags flags;
        [FieldOffset(24)]
        public IntPtr pInheritanceInfo;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkRenderPassBeginInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkRenderPass renderPass;
        [FieldOffset(24)]
        public VkFramebuffer framebuffer;
        [FieldOffset(32)]
        public VkRect2D renderArea;
        [FieldOffset(48)]
        public uint clearValueCount;
        [FieldOffset(56)]
        public IntPtr pClearValues;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkClearColorValue {
        [FieldOffset(0)]
        public float float32;
        [FieldOffset(0)]
        public int int32;
        [FieldOffset(0)]
        public uint uint32;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public struct VkClearDepthStencilValue {
        [FieldOffset(0)]
        public float depth;
        [FieldOffset(4)]
        public uint stencil;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkClearValue {
        [FieldOffset(0)]
        public VkClearColorValue color;
        [FieldOffset(0)]
        public VkClearDepthStencilValue depthStencil;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkClearAttachment {
        [FieldOffset(0)]
        public VkImageAspectFlags aspectMask;
        [FieldOffset(4)]
        public uint colorAttachment;
        [FieldOffset(8)]
        public VkClearValue clearValue;
    }

    [StructLayout(LayoutKind.Explicit, Size = 36)]
    public struct VkAttachmentDescription {
        [FieldOffset(0)]
        public VkAttachmentDescriptionFlags flags;
        [FieldOffset(4)]
        public VkFormat format;
        [FieldOffset(8)]
        public VkSampleCountFlags samples;
        [FieldOffset(12)]
        public VkAttachmentLoadOp loadOp;
        [FieldOffset(16)]
        public VkAttachmentStoreOp storeOp;
        [FieldOffset(20)]
        public VkAttachmentLoadOp stencilLoadOp;
        [FieldOffset(24)]
        public VkAttachmentStoreOp stencilStoreOp;
        [FieldOffset(28)]
        public VkImageLayout initialLayout;
        [FieldOffset(32)]
        public VkImageLayout finalLayout;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public struct VkAttachmentReference {
        [FieldOffset(0)]
        public uint attachment;
        [FieldOffset(4)]
        public VkImageLayout layout;
    }

    [StructLayout(LayoutKind.Explicit, Size = 72)]
    public struct VkSubpassDescription {
        [FieldOffset(0)]
        public VkSubpassDescriptionFlags flags;
        [FieldOffset(4)]
        public VkPipelineBindPoint pipelineBindPoint;
        [FieldOffset(8)]
        public uint inputAttachmentCount;
        [FieldOffset(16)]
        public IntPtr pInputAttachments;
        [FieldOffset(24)]
        public uint colorAttachmentCount;
        [FieldOffset(32)]
        public IntPtr pColorAttachments;
        [FieldOffset(40)]
        public IntPtr pResolveAttachments;
        [FieldOffset(48)]
        public IntPtr pDepthStencilAttachment;
        [FieldOffset(56)]
        public uint preserveAttachmentCount;
        [FieldOffset(64)]
        public IntPtr pPreserveAttachments;
    }

    [StructLayout(LayoutKind.Explicit, Size = 28)]
    public struct VkSubpassDependency {
        [FieldOffset(0)]
        public uint srcSubpass;
        [FieldOffset(4)]
        public uint dstSubpass;
        [FieldOffset(8)]
        public VkPipelineStageFlags srcStageMask;
        [FieldOffset(12)]
        public VkPipelineStageFlags dstStageMask;
        [FieldOffset(16)]
        public VkAccessFlags srcAccessMask;
        [FieldOffset(20)]
        public VkAccessFlags dstAccessMask;
        [FieldOffset(24)]
        public VkDependencyFlags dependencyFlags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkRenderPassCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkRenderPassCreateFlags flags;
        [FieldOffset(20)]
        public uint attachmentCount;
        [FieldOffset(24)]
        public IntPtr pAttachments;
        [FieldOffset(32)]
        public uint subpassCount;
        [FieldOffset(40)]
        public IntPtr pSubpasses;
        [FieldOffset(48)]
        public uint dependencyCount;
        [FieldOffset(56)]
        public IntPtr pDependencies;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkEventCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkEventCreateFlags flags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkFenceCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkFenceCreateFlags flags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 220)]
    public struct VkPhysicalDeviceFeatures {
        [FieldOffset(0)]
        public uint robustBufferAccess;
        [FieldOffset(4)]
        public uint fullDrawIndexUint32;
        [FieldOffset(8)]
        public uint imageCubeArray;
        [FieldOffset(12)]
        public uint independentBlend;
        [FieldOffset(16)]
        public uint geometryShader;
        [FieldOffset(20)]
        public uint tessellationShader;
        [FieldOffset(24)]
        public uint sampleRateShading;
        [FieldOffset(28)]
        public uint dualSrcBlend;
        [FieldOffset(32)]
        public uint logicOp;
        [FieldOffset(36)]
        public uint multiDrawIndirect;
        [FieldOffset(40)]
        public uint drawIndirectFirstInstance;
        [FieldOffset(44)]
        public uint depthClamp;
        [FieldOffset(48)]
        public uint depthBiasClamp;
        [FieldOffset(52)]
        public uint fillModeNonSolid;
        [FieldOffset(56)]
        public uint depthBounds;
        [FieldOffset(60)]
        public uint wideLines;
        [FieldOffset(64)]
        public uint largePoints;
        [FieldOffset(68)]
        public uint alphaToOne;
        [FieldOffset(72)]
        public uint multiViewport;
        [FieldOffset(76)]
        public uint samplerAnisotropy;
        [FieldOffset(80)]
        public uint textureCompressionETC2;
        [FieldOffset(84)]
        public uint textureCompressionASTC_LDR;
        [FieldOffset(88)]
        public uint textureCompressionBC;
        [FieldOffset(92)]
        public uint occlusionQueryPrecise;
        [FieldOffset(96)]
        public uint pipelineStatisticsQuery;
        [FieldOffset(100)]
        public uint vertexPipelineStoresAndAtomics;
        [FieldOffset(104)]
        public uint fragmentStoresAndAtomics;
        [FieldOffset(108)]
        public uint shaderTessellationAndGeometryPointSize;
        [FieldOffset(112)]
        public uint shaderImageGatherExtended;
        [FieldOffset(116)]
        public uint shaderStorageImageExtendedFormats;
        [FieldOffset(120)]
        public uint shaderStorageImageMultisample;
        [FieldOffset(124)]
        public uint shaderStorageImageReadWithoutFormat;
        [FieldOffset(128)]
        public uint shaderStorageImageWriteWithoutFormat;
        [FieldOffset(132)]
        public uint shaderUniformBufferArrayDynamicIndexing;
        [FieldOffset(136)]
        public uint shaderSampledImageArrayDynamicIndexing;
        [FieldOffset(140)]
        public uint shaderStorageBufferArrayDynamicIndexing;
        [FieldOffset(144)]
        public uint shaderStorageImageArrayDynamicIndexing;
        [FieldOffset(148)]
        public uint shaderClipDistance;
        [FieldOffset(152)]
        public uint shaderCullDistance;
        [FieldOffset(156)]
        public uint shaderFloat64;
        [FieldOffset(160)]
        public uint shaderInt64;
        [FieldOffset(164)]
        public uint shaderInt16;
        [FieldOffset(168)]
        public uint shaderResourceResidency;
        [FieldOffset(172)]
        public uint shaderResourceMinLod;
        [FieldOffset(176)]
        public uint sparseBinding;
        [FieldOffset(180)]
        public uint sparseResidencyBuffer;
        [FieldOffset(184)]
        public uint sparseResidencyImage2D;
        [FieldOffset(188)]
        public uint sparseResidencyImage3D;
        [FieldOffset(192)]
        public uint sparseResidency2Samples;
        [FieldOffset(196)]
        public uint sparseResidency4Samples;
        [FieldOffset(200)]
        public uint sparseResidency8Samples;
        [FieldOffset(204)]
        public uint sparseResidency16Samples;
        [FieldOffset(208)]
        public uint sparseResidencyAliased;
        [FieldOffset(212)]
        public uint variableMultisampleRate;
        [FieldOffset(216)]
        public uint inheritedQueries;
    }

    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public struct VkPhysicalDeviceSparseProperties {
        [FieldOffset(0)]
        public uint residencyStandard2DBlockShape;
        [FieldOffset(4)]
        public uint residencyStandard2DMultisampleBlockShape;
        [FieldOffset(8)]
        public uint residencyStandard3DBlockShape;
        [FieldOffset(12)]
        public uint residencyAlignedMipSize;
        [FieldOffset(16)]
        public uint residencyNonResidentStrict;
    }

    [StructLayout(LayoutKind.Explicit, Size = 504)]
    public struct VkPhysicalDeviceLimits {
        [FieldOffset(0)]
        public uint maxImageDimension1D;
        [FieldOffset(4)]
        public uint maxImageDimension2D;
        [FieldOffset(8)]
        public uint maxImageDimension3D;
        [FieldOffset(12)]
        public uint maxImageDimensionCube;
        [FieldOffset(16)]
        public uint maxImageArrayLayers;
        [FieldOffset(20)]
        public uint maxTexelBufferElements;
        [FieldOffset(24)]
        public uint maxUniformBufferRange;
        [FieldOffset(28)]
        public uint maxStorageBufferRange;
        [FieldOffset(32)]
        public uint maxPushConstantsSize;
        [FieldOffset(36)]
        public uint maxMemoryAllocationCount;
        [FieldOffset(40)]
        public uint maxSamplerAllocationCount;
        [FieldOffset(48)]
        public ulong bufferImageGranularity;
        [FieldOffset(56)]
        public ulong sparseAddressSpaceSize;
        [FieldOffset(64)]
        public uint maxBoundDescriptorSets;
        [FieldOffset(68)]
        public uint maxPerStageDescriptorSamplers;
        [FieldOffset(72)]
        public uint maxPerStageDescriptorUniformBuffers;
        [FieldOffset(76)]
        public uint maxPerStageDescriptorStorageBuffers;
        [FieldOffset(80)]
        public uint maxPerStageDescriptorSampledImages;
        [FieldOffset(84)]
        public uint maxPerStageDescriptorStorageImages;
        [FieldOffset(88)]
        public uint maxPerStageDescriptorInputAttachments;
        [FieldOffset(92)]
        public uint maxPerStageResources;
        [FieldOffset(96)]
        public uint maxDescriptorSetSamplers;
        [FieldOffset(100)]
        public uint maxDescriptorSetUniformBuffers;
        [FieldOffset(104)]
        public uint maxDescriptorSetUniformBuffersDynamic;
        [FieldOffset(108)]
        public uint maxDescriptorSetStorageBuffers;
        [FieldOffset(112)]
        public uint maxDescriptorSetStorageBuffersDynamic;
        [FieldOffset(116)]
        public uint maxDescriptorSetSampledImages;
        [FieldOffset(120)]
        public uint maxDescriptorSetStorageImages;
        [FieldOffset(124)]
        public uint maxDescriptorSetInputAttachments;
        [FieldOffset(128)]
        public uint maxVertexInputAttributes;
        [FieldOffset(132)]
        public uint maxVertexInputBindings;
        [FieldOffset(136)]
        public uint maxVertexInputAttributeOffset;
        [FieldOffset(140)]
        public uint maxVertexInputBindingStride;
        [FieldOffset(144)]
        public uint maxVertexOutputComponents;
        [FieldOffset(148)]
        public uint maxTessellationGenerationLevel;
        [FieldOffset(152)]
        public uint maxTessellationPatchSize;
        [FieldOffset(156)]
        public uint maxTessellationControlPerVertexInputComponents;
        [FieldOffset(160)]
        public uint maxTessellationControlPerVertexOutputComponents;
        [FieldOffset(164)]
        public uint maxTessellationControlPerPatchOutputComponents;
        [FieldOffset(168)]
        public uint maxTessellationControlTotalOutputComponents;
        [FieldOffset(172)]
        public uint maxTessellationEvaluationInputComponents;
        [FieldOffset(176)]
        public uint maxTessellationEvaluationOutputComponents;
        [FieldOffset(180)]
        public uint maxGeometryShaderInvocations;
        [FieldOffset(184)]
        public uint maxGeometryInputComponents;
        [FieldOffset(188)]
        public uint maxGeometryOutputComponents;
        [FieldOffset(192)]
        public uint maxGeometryOutputVertices;
        [FieldOffset(196)]
        public uint maxGeometryTotalOutputComponents;
        [FieldOffset(200)]
        public uint maxFragmentInputComponents;
        [FieldOffset(204)]
        public uint maxFragmentOutputAttachments;
        [FieldOffset(208)]
        public uint maxFragmentDualSrcAttachments;
        [FieldOffset(212)]
        public uint maxFragmentCombinedOutputResources;
        [FieldOffset(216)]
        public uint maxComputeSharedMemorySize;
        [FieldOffset(220)]
        public uint maxComputeWorkGroupCount;
        [FieldOffset(232)]
        public uint maxComputeWorkGroupInvocations;
        [FieldOffset(236)]
        public uint maxComputeWorkGroupSize;
        [FieldOffset(248)]
        public uint subPixelPrecisionBits;
        [FieldOffset(252)]
        public uint subTexelPrecisionBits;
        [FieldOffset(256)]
        public uint mipmapPrecisionBits;
        [FieldOffset(260)]
        public uint maxDrawIndexedIndexValue;
        [FieldOffset(264)]
        public uint maxDrawIndirectCount;
        [FieldOffset(268)]
        public float maxSamplerLodBias;
        [FieldOffset(272)]
        public float maxSamplerAnisotropy;
        [FieldOffset(276)]
        public uint maxViewports;
        [FieldOffset(280)]
        public uint maxViewportDimensions;
        [FieldOffset(288)]
        public float viewportBoundsRange;
        [FieldOffset(296)]
        public uint viewportSubPixelBits;
        [FieldOffset(304)]
        public ulong minMemoryMapAlignment;
        [FieldOffset(312)]
        public ulong minTexelBufferOffsetAlignment;
        [FieldOffset(320)]
        public ulong minUniformBufferOffsetAlignment;
        [FieldOffset(328)]
        public ulong minStorageBufferOffsetAlignment;
        [FieldOffset(336)]
        public int minTexelOffset;
        [FieldOffset(340)]
        public uint maxTexelOffset;
        [FieldOffset(344)]
        public int minTexelGatherOffset;
        [FieldOffset(348)]
        public uint maxTexelGatherOffset;
        [FieldOffset(352)]
        public float minInterpolationOffset;
        [FieldOffset(356)]
        public float maxInterpolationOffset;
        [FieldOffset(360)]
        public uint subPixelInterpolationOffsetBits;
        [FieldOffset(364)]
        public uint maxFramebufferWidth;
        [FieldOffset(368)]
        public uint maxFramebufferHeight;
        [FieldOffset(372)]
        public uint maxFramebufferLayers;
        [FieldOffset(376)]
        public VkSampleCountFlags framebufferColorSampleCounts;
        [FieldOffset(380)]
        public VkSampleCountFlags framebufferDepthSampleCounts;
        [FieldOffset(384)]
        public VkSampleCountFlags framebufferStencilSampleCounts;
        [FieldOffset(388)]
        public VkSampleCountFlags framebufferNoAttachmentsSampleCounts;
        [FieldOffset(392)]
        public uint maxColorAttachments;
        [FieldOffset(396)]
        public VkSampleCountFlags sampledImageColorSampleCounts;
        [FieldOffset(400)]
        public VkSampleCountFlags sampledImageIntegerSampleCounts;
        [FieldOffset(404)]
        public VkSampleCountFlags sampledImageDepthSampleCounts;
        [FieldOffset(408)]
        public VkSampleCountFlags sampledImageStencilSampleCounts;
        [FieldOffset(412)]
        public VkSampleCountFlags storageImageSampleCounts;
        [FieldOffset(416)]
        public uint maxSampleMaskWords;
        [FieldOffset(420)]
        public uint timestampComputeAndGraphics;
        [FieldOffset(424)]
        public float timestampPeriod;
        [FieldOffset(428)]
        public uint maxClipDistances;
        [FieldOffset(432)]
        public uint maxCullDistances;
        [FieldOffset(436)]
        public uint maxCombinedClipAndCullDistances;
        [FieldOffset(440)]
        public uint discreteQueuePriorities;
        [FieldOffset(444)]
        public float pointSizeRange;
        [FieldOffset(452)]
        public float lineWidthRange;
        [FieldOffset(460)]
        public float pointSizeGranularity;
        [FieldOffset(464)]
        public float lineWidthGranularity;
        [FieldOffset(468)]
        public uint strictLines;
        [FieldOffset(472)]
        public uint standardSampleLocations;
        [FieldOffset(480)]
        public ulong optimalBufferCopyOffsetAlignment;
        [FieldOffset(488)]
        public ulong optimalBufferCopyRowPitchAlignment;
        [FieldOffset(496)]
        public ulong nonCoherentAtomSize;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkSemaphoreCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkSemaphoreCreateFlags flags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkQueryPoolCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkQueryPoolCreateFlags flags;
        [FieldOffset(20)]
        public VkQueryType queryType;
        [FieldOffset(24)]
        public uint queryCount;
        [FieldOffset(28)]
        public VkQueryPipelineStatisticFlags pipelineStatistics;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkFramebufferCreateInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkFramebufferCreateFlags flags;
        [FieldOffset(24)]
        public VkRenderPass renderPass;
        [FieldOffset(32)]
        public uint attachmentCount;
        [FieldOffset(40)]
        public IntPtr pAttachments;
        [FieldOffset(48)]
        public uint width;
        [FieldOffset(52)]
        public uint height;
        [FieldOffset(56)]
        public uint layers;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkDrawIndirectCommand {
        [FieldOffset(0)]
        public uint vertexCount;
        [FieldOffset(4)]
        public uint instanceCount;
        [FieldOffset(8)]
        public uint firstVertex;
        [FieldOffset(12)]
        public uint firstInstance;
    }

    [StructLayout(LayoutKind.Explicit, Size = 20)]
    public struct VkDrawIndexedIndirectCommand {
        [FieldOffset(0)]
        public uint indexCount;
        [FieldOffset(4)]
        public uint instanceCount;
        [FieldOffset(8)]
        public uint firstIndex;
        [FieldOffset(12)]
        public int vertexOffset;
        [FieldOffset(16)]
        public uint firstInstance;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkDispatchIndirectCommand {
        [FieldOffset(0)]
        public uint x;
        [FieldOffset(4)]
        public uint y;
        [FieldOffset(8)]
        public uint z;
    }

    [StructLayout(LayoutKind.Explicit, Size = 72)]
    public struct VkSubmitInfo {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public uint waitSemaphoreCount;
        [FieldOffset(24)]
        public IntPtr pWaitSemaphores;
        [FieldOffset(32)]
        public IntPtr pWaitDstStageMask;
        [FieldOffset(40)]
        public uint commandBufferCount;
        [FieldOffset(48)]
        public IntPtr pCommandBuffers;
        [FieldOffset(56)]
        public uint signalSemaphoreCount;
        [FieldOffset(64)]
        public IntPtr pSignalSemaphores;
    }

    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public struct VkDisplayPropertiesKHR {
        [FieldOffset(0)]
        public VkDisplayKHR display;
        [FieldOffset(8)]
        public IntPtr displayName;
        [FieldOffset(16)]
        public VkExtent2D physicalDimensions;
        [FieldOffset(24)]
        public VkExtent2D physicalResolution;
        [FieldOffset(32)]
        public VkSurfaceTransformFlagsKHR supportedTransforms;
        [FieldOffset(36)]
        public uint planeReorderPossible;
        [FieldOffset(40)]
        public uint persistentContent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public struct VkDisplayPlanePropertiesKHR {
        [FieldOffset(0)]
        public VkDisplayKHR currentDisplay;
        [FieldOffset(8)]
        public uint currentStackIndex;
    }

    [StructLayout(LayoutKind.Explicit, Size = 12)]
    public struct VkDisplayModeParametersKHR {
        [FieldOffset(0)]
        public VkExtent2D visibleRegion;
        [FieldOffset(8)]
        public uint refreshRate;
    }

    [StructLayout(LayoutKind.Explicit, Size = 24)]
    public struct VkDisplayModePropertiesKHR {
        [FieldOffset(0)]
        public VkDisplayModeKHR displayMode;
        [FieldOffset(8)]
        public VkDisplayModeParametersKHR parameters;
    }

    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public struct VkDisplayModeCreateInfoKHR {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDisplayModeCreateFlagsKHR flags;
        [FieldOffset(20)]
        public VkDisplayModeParametersKHR parameters;
    }

    [StructLayout(LayoutKind.Explicit, Size = 68)]
    public struct VkDisplayPlaneCapabilitiesKHR {
        [FieldOffset(0)]
        public VkDisplayPlaneAlphaFlagsKHR supportedAlpha;
        [FieldOffset(4)]
        public VkOffset2D minSrcPosition;
        [FieldOffset(12)]
        public VkOffset2D maxSrcPosition;
        [FieldOffset(20)]
        public VkExtent2D minSrcExtent;
        [FieldOffset(28)]
        public VkExtent2D maxSrcExtent;
        [FieldOffset(36)]
        public VkOffset2D minDstPosition;
        [FieldOffset(44)]
        public VkOffset2D maxDstPosition;
        [FieldOffset(52)]
        public VkExtent2D minDstExtent;
        [FieldOffset(60)]
        public VkExtent2D maxDstExtent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkDisplaySurfaceCreateInfoKHR {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDisplaySurfaceCreateFlagsKHR flags;
        [FieldOffset(24)]
        public VkDisplayModeKHR displayMode;
        [FieldOffset(32)]
        public uint planeIndex;
        [FieldOffset(36)]
        public uint planeStackIndex;
        [FieldOffset(40)]
        public VkSurfaceTransformFlagsKHR transform;
        [FieldOffset(44)]
        public float globalAlpha;
        [FieldOffset(48)]
        public VkDisplayPlaneAlphaFlagsKHR alphaMode;
        [FieldOffset(52)]
        public VkExtent2D imageExtent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public struct VkDisplayPresentInfoKHR {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkRect2D srcRect;
        [FieldOffset(32)]
        public VkRect2D dstRect;
        [FieldOffset(48)]
        public uint persistent;
    }

    [StructLayout(LayoutKind.Explicit, Size = 52)]
    public struct VkSurfaceCapabilitiesKHR {
        [FieldOffset(0)]
        public uint minImageCount;
        [FieldOffset(4)]
        public uint maxImageCount;
        [FieldOffset(8)]
        public VkExtent2D currentExtent;
        [FieldOffset(16)]
        public VkExtent2D minImageExtent;
        [FieldOffset(24)]
        public VkExtent2D maxImageExtent;
        [FieldOffset(32)]
        public uint maxImageArrayLayers;
        [FieldOffset(36)]
        public VkSurfaceTransformFlagsKHR supportedTransforms;
        [FieldOffset(40)]
        public VkSurfaceTransformFlagsKHR currentTransform;
        [FieldOffset(44)]
        public VkCompositeAlphaFlagsKHR supportedCompositeAlpha;
        [FieldOffset(48)]
        public VkImageUsageFlags supportedUsageFlags;
    }

    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public struct VkSurfaceFormatKHR {
        [FieldOffset(0)]
        public VkFormat format;
        [FieldOffset(4)]
        public VkColorSpaceKHR colorSpace;
    }

    [StructLayout(LayoutKind.Explicit, Size = 104)]
    public struct VkSwapchainCreateInfoKHR {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkSwapchainCreateFlagsKHR flags;
        [FieldOffset(24)]
        public VkSurfaceKHR surface;
        [FieldOffset(32)]
        public uint minImageCount;
        [FieldOffset(36)]
        public VkFormat imageFormat;
        [FieldOffset(40)]
        public VkColorSpaceKHR imageColorSpace;
        [FieldOffset(44)]
        public VkExtent2D imageExtent;
        [FieldOffset(52)]
        public uint imageArrayLayers;
        [FieldOffset(56)]
        public VkImageUsageFlags imageUsage;
        [FieldOffset(60)]
        public VkSharingMode imageSharingMode;
        [FieldOffset(64)]
        public uint queueFamilyIndexCount;
        [FieldOffset(72)]
        public IntPtr pQueueFamilyIndices;
        [FieldOffset(80)]
        public VkSurfaceTransformFlagsKHR preTransform;
        [FieldOffset(84)]
        public VkCompositeAlphaFlagsKHR compositeAlpha;
        [FieldOffset(88)]
        public VkPresentModeKHR presentMode;
        [FieldOffset(92)]
        public uint clipped;
        [FieldOffset(96)]
        public VkSwapchainKHR oldSwapchain;
    }

    [StructLayout(LayoutKind.Explicit, Size = 64)]
    public struct VkPresentInfoKHR {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public uint waitSemaphoreCount;
        [FieldOffset(24)]
        public IntPtr pWaitSemaphores;
        [FieldOffset(32)]
        public uint swapchainCount;
        [FieldOffset(40)]
        public IntPtr pSwapchains;
        [FieldOffset(48)]
        public IntPtr pImageIndices;
        [FieldOffset(56)]
        public IntPtr pResults;
    }

    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public struct VkDebugReportCallbackCreateInfoEXT {
        [FieldOffset(0)]
        public VkStructureType sType;
        [FieldOffset(8)]
        public IntPtr pNext;
        [FieldOffset(16)]
        public VkDebugReportFlagsEXT flags;
        [FieldOffset(24)]
        public IntPtr pfnCallback;
        [FieldOffset(32)]
        public IntPtr pUserData;
    }

}
