//autogenerated on 09/09/2017 6:16:51 PM
using System;

namespace CSGL.Vulkan {
    [Flags]
    public enum VkFramebufferCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkQueryPoolCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkRenderPassCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkSamplerCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineLayoutCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineCacheCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineDepthStencilStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineDynamicStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineColorBlendStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineMultisampleStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineRasterizationStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineViewportStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineTessellationStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineInputAssemblyStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineVertexInputStateCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineShaderStageCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDescriptorSetLayoutCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkBufferViewCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkInstanceCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDeviceCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDeviceQueueCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkQueueFlags : uint {
        None = 0,
        GraphicsBit = 1,
        ComputeBit = 2,
        TransferBit = 4,
        SparseBindingBit = 8,
    }

    [Flags]
    public enum VkMemoryPropertyFlags : uint {
        None = 0,
        DeviceLocalBit = 1,
        HostVisibleBit = 2,
        HostCoherentBit = 4,
        HostCachedBit = 8,
        LazilyAllocatedBit = 16,
    }

    [Flags]
    public enum VkMemoryHeapFlags : uint {
        None = 0,
        DeviceLocalBit = 1,
    }

    [Flags]
    public enum VkAccessFlags : uint {
        None = 0,
        IndirectCommandReadBit = 1,
        IndexReadBit = 2,
        VertexAttributeReadBit = 4,
        UniformReadBit = 8,
        InputAttachmentReadBit = 16,
        ShaderReadBit = 32,
        ShaderWriteBit = 64,
        ColorAttachmentReadBit = 128,
        ColorAttachmentWriteBit = 256,
        DepthStencilAttachmentReadBit = 512,
        DepthStencilAttachmentWriteBit = 1024,
        TransferReadBit = 2048,
        TransferWriteBit = 4096,
        HostReadBit = 8192,
        HostWriteBit = 16384,
        MemoryReadBit = 32768,
        MemoryWriteBit = 65536,
    }

    [Flags]
    public enum VkBufferUsageFlags : uint {
        None = 0,
        TransferSrcBit = 1,
        TransferDstBit = 2,
        UniformTexelBufferBit = 4,
        StorageTexelBufferBit = 8,
        UniformBufferBit = 16,
        StorageBufferBit = 32,
        IndexBufferBit = 64,
        VertexBufferBit = 128,
        IndirectBufferBit = 256,
    }

    [Flags]
    public enum VkBufferCreateFlags : uint {
        None = 0,
        SparseBindingBit = 1,
        SparseResidencyBit = 2,
        SparseAliasedBit = 4,
    }

    [Flags]
    public enum VkShaderStageFlags : uint {
        None = 0,
        VertexBit = 1,
        TessellationControlBit = 2,
        TessellationEvaluationBit = 4,
        GeometryBit = 8,
        FragmentBit = 16,
        ComputeBit = 32,
        AllGraphics = 0x0000001F,
        All = 0x7FFFFFFF,
    }

    [Flags]
    public enum VkImageUsageFlags : uint {
        None = 0,
        TransferSrcBit = 1,
        TransferDstBit = 2,
        SampledBit = 4,
        StorageBit = 8,
        ColorAttachmentBit = 16,
        DepthStencilAttachmentBit = 32,
        TransientAttachmentBit = 64,
        InputAttachmentBit = 128,
    }

    [Flags]
    public enum VkImageCreateFlags : uint {
        None = 0,
        SparseBindingBit = 1,
        SparseResidencyBit = 2,
        SparseAliasedBit = 4,
        MutableFormatBit = 8,
        CubeCompatibleBit = 16,
    }

    [Flags]
    public enum VkImageViewCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineCreateFlags : uint {
        None = 0,
        DisableOptimizationBit = 1,
        AllowDerivativesBit = 2,
        DerivativeBit = 4,
    }

    [Flags]
    public enum VkColorComponentFlags : uint {
        None = 0,
        RBit = 1,
        GBit = 2,
        BBit = 4,
        ABit = 8,
    }

    [Flags]
    public enum VkFenceCreateFlags : uint {
        None = 0,
        SignaledBit = 1,
    }

    [Flags]
    public enum VkSemaphoreCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkFormatFeatureFlags : uint {
        None = 0,
        SampledImageBit = 1,
        StorageImageBit = 2,
        StorageImageAtomicBit = 4,
        UniformTexelBufferBit = 8,
        StorageTexelBufferBit = 16,
        StorageTexelBufferAtomicBit = 32,
        VertexBufferBit = 64,
        ColorAttachmentBit = 128,
        ColorAttachmentBlendBit = 256,
        DepthStencilAttachmentBit = 512,
        BlitSrcBit = 1024,
        BlitDstBit = 2048,
        SampledImageFilterLinearBit = 4096,
    }

    [Flags]
    public enum VkQueryControlFlags : uint {
        None = 0,
        PreciseBit = 1,
    }

    [Flags]
    public enum VkQueryResultFlags : uint {
        None = 0,
        _64_Bit = 1,
        WaitBit = 2,
        WithAvailabilityBit = 4,
        PartialBit = 8,
    }

    [Flags]
    public enum VkShaderModuleCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkEventCreateFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkCommandPoolCreateFlags : uint {
        None = 0,
        TransientBit = 1,
        ResetCommandBufferBit = 2,
    }

    [Flags]
    public enum VkCommandPoolResetFlags : uint {
        None = 0,
        ReleaseResourcesBit = 1,
    }

    [Flags]
    public enum VkCommandBufferResetFlags : uint {
        None = 0,
        ReleaseResourcesBit = 1,
    }

    [Flags]
    public enum VkCommandBufferUsageFlags : uint {
        None = 0,
        OneTimeSubmitBit = 1,
        RenderPassContinueBit = 2,
        SimultaneousUseBit = 4,
    }

    [Flags]
    public enum VkQueryPipelineStatisticFlags : uint {
        None = 0,
        InputAssemblyVerticesBit = 1,
        InputAssemblyPrimitivesBit = 2,
        VertexShaderInvocationsBit = 4,
        GeometryShaderInvocationsBit = 8,
        GeometryShaderPrimitivesBit = 16,
        ClippingInvocationsBit = 32,
        ClippingPrimitivesBit = 64,
        FragmentShaderInvocationsBit = 128,
        TessellationControlShaderPatchesBit = 256,
        TessellationEvaluationShaderInvocationsBit = 512,
        ComputeShaderInvocationsBit = 1024,
    }

    [Flags]
    public enum VkMemoryMapFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkImageAspectFlags : uint {
        None = 0,
        ColorBit = 1,
        DepthBit = 2,
        StencilBit = 4,
        MetadataBit = 8,
    }

    [Flags]
    public enum VkSparseMemoryBindFlags : uint {
        None = 0,
        MetadataBit = 1,
    }

    [Flags]
    public enum VkSparseImageFormatFlags : uint {
        None = 0,
        SingleMiptailBit = 1,
        AlignedMipSizeBit = 2,
        NonstandardBlockSizeBit = 4,
    }

    [Flags]
    public enum VkSubpassDescriptionFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkPipelineStageFlags : uint {
        None = 0,
        TopOfPipeBit = 1,
        DrawIndirectBit = 2,
        VertexInputBit = 4,
        VertexShaderBit = 8,
        TessellationControlShaderBit = 16,
        TessellationEvaluationShaderBit = 32,
        GeometryShaderBit = 64,
        FragmentShaderBit = 128,
        EarlyFragmentTestsBit = 256,
        LateFragmentTestsBit = 512,
        ColorAttachmentOutputBit = 1024,
        ComputeShaderBit = 2048,
        TransferBit = 4096,
        BottomOfPipeBit = 8192,
        HostBit = 16384,
        AllGraphicsBit = 32768,
        AllCommandsBit = 65536,
    }

    [Flags]
    public enum VkSampleCountFlags : uint {
        None = 0,
        _1_Bit = 1,
        _2_Bit = 2,
        _4_Bit = 4,
        _8_Bit = 8,
        _16_Bit = 16,
        _32_Bit = 32,
        _64_Bit = 64,
    }

    [Flags]
    public enum VkAttachmentDescriptionFlags : uint {
        None = 0,
        MayAliasBit = 1,
    }

    [Flags]
    public enum VkStencilFaceFlags : uint {
        None = 0,
        FrontBit = 1,
        BackBit = 2,
        FrontAndBack = 0x00000003,
    }

    [Flags]
    public enum VkCullModeFlags : uint {
        None = 0,
        FrontBit = 1,
        BackBit = 2,
        FrontAndBack = 0x00000003,
    }

    [Flags]
    public enum VkDescriptorPoolCreateFlags : uint {
        None = 0,
        FreeDescriptorSetBit = 1,
    }

    [Flags]
    public enum VkDescriptorPoolResetFlags : uint {
        None = 0,
    }

    [Flags]
    public enum VkDependencyFlags : uint {
        None = 0,
        ByRegionBit = 1,
    }

    [Flags]
    public enum VkCompositeAlphaFlagsKHR : uint {
        None = 0,
        OpaqueBitKhr = 1,
        PreMultipliedBitKhr = 2,
        PostMultipliedBitKhr = 4,
        InheritBitKhr = 8,
    }

    [Flags]
    public enum VkSurfaceTransformFlagsKHR : uint {
        None = 0,
        IdentityBitKhr = 1,
        Rotate_90_BitKhr = 2,
        Rotate_180_BitKhr = 4,
        Rotate_270_BitKhr = 8,
        HorizontalMirrorBitKhr = 16,
        HorizontalMirrorRotate_90_BitKhr = 32,
        HorizontalMirrorRotate_180_BitKhr = 64,
        HorizontalMirrorRotate_270_BitKhr = 128,
        InheritBitKhr = 256,
    }

    [Flags]
    public enum VkSwapchainCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkDisplayModeCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkDisplaySurfaceCreateFlagsKHR : uint {
        None = 0,
    }

    [Flags]
    public enum VkDebugReportFlagsEXT : uint {
        None = 0,
        InformationBitExt = 1,
        WarningBitExt = 2,
        PerformanceWarningBitExt = 4,
        ErrorBitExt = 8,
        DebugBitExt = 16,
    }

    [Flags]
    public enum VkCommandPoolTrimFlagsKHR : uint {
        None = 0,
    }

    public enum VkAttachmentLoadOp {
        Load = 0,
        Clear = 1,
        DontCare = 2,
    }

    public enum VkAttachmentStoreOp {
        Store = 0,
        DontCare = 1,
    }

    public enum VkBlendFactor {
        Zero = 0,
        One = 1,
        SrcColor = 2,
        OneMinusSrcColor = 3,
        DstColor = 4,
        OneMinusDstColor = 5,
        SrcAlpha = 6,
        OneMinusSrcAlpha = 7,
        DstAlpha = 8,
        OneMinusDstAlpha = 9,
        ConstantColor = 10,
        OneMinusConstantColor = 11,
        ConstantAlpha = 12,
        OneMinusConstantAlpha = 13,
        SrcAlphaSaturate = 14,
        SRC1_Color = 15,
        OneMinus_SRC1_Color = 16,
        SRC1_Alpha = 17,
        OneMinus_SRC1_Alpha = 18,
    }

    public enum VkBlendOp {
        Add = 0,
        Subtract = 1,
        ReverseSubtract = 2,
        Min = 3,
        Max = 4,
    }

    public enum VkBorderColor {
        FloatTransparentBlack = 0,
        IntTransparentBlack = 1,
        FloatOpaqueBlack = 2,
        IntOpaqueBlack = 3,
        FloatOpaqueWhite = 4,
        IntOpaqueWhite = 5,
    }

    public enum VkPipelineCacheHeaderVersion {
        One = 1,
    }

    public enum VkComponentSwizzle {
        Identity = 0,
        Zero = 1,
        One = 2,
        R = 3,
        G = 4,
        B = 5,
        A = 6,
    }

    public enum VkCommandBufferLevel {
        Primary = 0,
        Secondary = 1,
    }

    public enum VkCompareOp {
        Never = 0,
        Less = 1,
        Equal = 2,
        LessOrEqual = 3,
        Greater = 4,
        NotEqual = 5,
        GreaterOrEqual = 6,
        Always = 7,
    }

    public enum VkDescriptorType {
        Sampler = 0,
        CombinedImageSampler = 1,
        SampledImage = 2,
        StorageImage = 3,
        UniformTexelBuffer = 4,
        StorageTexelBuffer = 5,
        UniformBuffer = 6,
        StorageBuffer = 7,
        UniformBufferDynamic = 8,
        StorageBufferDynamic = 9,
        InputAttachment = 10,
    }

    public enum VkDynamicState {
        Viewport = 0,
        Scissor = 1,
        LineWidth = 2,
        DepthBias = 3,
        BlendConstants = 4,
        DepthBounds = 5,
        StencilCompareMask = 6,
        StencilWriteMask = 7,
        StencilReference = 8,
    }

    public enum VkPolygonMode {
        Fill = 0,
        Line = 1,
        Point = 2,
    }

    public enum VkFormat {
        Undefined = 0,
        R4G4_Unorm_PACK8 = 1,
        R4G4B4A4_Unorm_PACK16 = 2,
        B4G4R4A4_Unorm_PACK16 = 3,
        R5G6B5_Unorm_PACK16 = 4,
        B5G6R5_Unorm_PACK16 = 5,
        R5G5B5A1_Unorm_PACK16 = 6,
        B5G5R5A1_Unorm_PACK16 = 7,
        A1R5G5B5_Unorm_PACK16 = 8,
        R8_Unorm = 9,
        R8_Snorm = 10,
        R8_Uscaled = 11,
        R8_Sscaled = 12,
        R8_Uint = 13,
        R8_Sint = 14,
        R8_Srgb = 15,
        R8G8_Unorm = 16,
        R8G8_Snorm = 17,
        R8G8_Uscaled = 18,
        R8G8_Sscaled = 19,
        R8G8_Uint = 20,
        R8G8_Sint = 21,
        R8G8_Srgb = 22,
        R8G8B8_Unorm = 23,
        R8G8B8_Snorm = 24,
        R8G8B8_Uscaled = 25,
        R8G8B8_Sscaled = 26,
        R8G8B8_Uint = 27,
        R8G8B8_Sint = 28,
        R8G8B8_Srgb = 29,
        B8G8R8_Unorm = 30,
        B8G8R8_Snorm = 31,
        B8G8R8_Uscaled = 32,
        B8G8R8_Sscaled = 33,
        B8G8R8_Uint = 34,
        B8G8R8_Sint = 35,
        B8G8R8_Srgb = 36,
        R8G8B8A8_Unorm = 37,
        R8G8B8A8_Snorm = 38,
        R8G8B8A8_Uscaled = 39,
        R8G8B8A8_Sscaled = 40,
        R8G8B8A8_Uint = 41,
        R8G8B8A8_Sint = 42,
        R8G8B8A8_Srgb = 43,
        B8G8R8A8_Unorm = 44,
        B8G8R8A8_Snorm = 45,
        B8G8R8A8_Uscaled = 46,
        B8G8R8A8_Sscaled = 47,
        B8G8R8A8_Uint = 48,
        B8G8R8A8_Sint = 49,
        B8G8R8A8_Srgb = 50,
        A8B8G8R8_Unorm_PACK32 = 51,
        A8B8G8R8_Snorm_PACK32 = 52,
        A8B8G8R8_Uscaled_PACK32 = 53,
        A8B8G8R8_Sscaled_PACK32 = 54,
        A8B8G8R8_Uint_PACK32 = 55,
        A8B8G8R8_Sint_PACK32 = 56,
        A8B8G8R8_Srgb_PACK32 = 57,
        A2R10G10B10_Unorm_PACK32 = 58,
        A2R10G10B10_Snorm_PACK32 = 59,
        A2R10G10B10_Uscaled_PACK32 = 60,
        A2R10G10B10_Sscaled_PACK32 = 61,
        A2R10G10B10_Uint_PACK32 = 62,
        A2R10G10B10_Sint_PACK32 = 63,
        A2B10G10R10_Unorm_PACK32 = 64,
        A2B10G10R10_Snorm_PACK32 = 65,
        A2B10G10R10_Uscaled_PACK32 = 66,
        A2B10G10R10_Sscaled_PACK32 = 67,
        A2B10G10R10_Uint_PACK32 = 68,
        A2B10G10R10_Sint_PACK32 = 69,
        R16_Unorm = 70,
        R16_Snorm = 71,
        R16_Uscaled = 72,
        R16_Sscaled = 73,
        R16_Uint = 74,
        R16_Sint = 75,
        R16_Sfloat = 76,
        R16G16_Unorm = 77,
        R16G16_Snorm = 78,
        R16G16_Uscaled = 79,
        R16G16_Sscaled = 80,
        R16G16_Uint = 81,
        R16G16_Sint = 82,
        R16G16_Sfloat = 83,
        R16G16B16_Unorm = 84,
        R16G16B16_Snorm = 85,
        R16G16B16_Uscaled = 86,
        R16G16B16_Sscaled = 87,
        R16G16B16_Uint = 88,
        R16G16B16_Sint = 89,
        R16G16B16_Sfloat = 90,
        R16G16B16A16_Unorm = 91,
        R16G16B16A16_Snorm = 92,
        R16G16B16A16_Uscaled = 93,
        R16G16B16A16_Sscaled = 94,
        R16G16B16A16_Uint = 95,
        R16G16B16A16_Sint = 96,
        R16G16B16A16_Sfloat = 97,
        R32_Uint = 98,
        R32_Sint = 99,
        R32_Sfloat = 100,
        R32G32_Uint = 101,
        R32G32_Sint = 102,
        R32G32_Sfloat = 103,
        R32G32B32_Uint = 104,
        R32G32B32_Sint = 105,
        R32G32B32_Sfloat = 106,
        R32G32B32A32_Uint = 107,
        R32G32B32A32_Sint = 108,
        R32G32B32A32_Sfloat = 109,
        R64_Uint = 110,
        R64_Sint = 111,
        R64_Sfloat = 112,
        R64G64_Uint = 113,
        R64G64_Sint = 114,
        R64G64_Sfloat = 115,
        R64G64B64_Uint = 116,
        R64G64B64_Sint = 117,
        R64G64B64_Sfloat = 118,
        R64G64B64A64_Uint = 119,
        R64G64B64A64_Sint = 120,
        R64G64B64A64_Sfloat = 121,
        B10G11R11_Ufloat_PACK32 = 122,
        E5B9G9R9_Ufloat_PACK32 = 123,
        D16_Unorm = 124,
        X8_D24_Unorm_PACK32 = 125,
        D32_Sfloat = 126,
        S8_Uint = 127,
        D16_Unorm_S8_Uint = 128,
        D24_Unorm_S8_Uint = 129,
        D32_Sfloat_S8_Uint = 130,
        BC1_RgbUnormBlock = 131,
        BC1_RgbSrgbBlock = 132,
        BC1_RgbaUnormBlock = 133,
        BC1_RgbaSrgbBlock = 134,
        BC2_UnormBlock = 135,
        BC2_SrgbBlock = 136,
        BC3_UnormBlock = 137,
        BC3_SrgbBlock = 138,
        BC4_UnormBlock = 139,
        BC4_SnormBlock = 140,
        BC5_UnormBlock = 141,
        BC5_SnormBlock = 142,
        BC6H_UfloatBlock = 143,
        BC6H_SfloatBlock = 144,
        BC7_UnormBlock = 145,
        BC7_SrgbBlock = 146,
        ETC2_R8G8B8_UnormBlock = 147,
        ETC2_R8G8B8_SrgbBlock = 148,
        ETC2_R8G8B8A1_UnormBlock = 149,
        ETC2_R8G8B8A1_SrgbBlock = 150,
        ETC2_R8G8B8A8_UnormBlock = 151,
        ETC2_R8G8B8A8_SrgbBlock = 152,
        Eac_R11_UnormBlock = 153,
        Eac_R11_SnormBlock = 154,
        Eac_R11G11_UnormBlock = 155,
        Eac_R11G11_SnormBlock = 156,
        Astc_4x4_UnormBlock = 157,
        Astc_4x4_SrgbBlock = 158,
        Astc_5x4_UnormBlock = 159,
        Astc_5x4_SrgbBlock = 160,
        Astc_5x5_UnormBlock = 161,
        Astc_5x5_SrgbBlock = 162,
        Astc_6x5_UnormBlock = 163,
        Astc_6x5_SrgbBlock = 164,
        Astc_6x6_UnormBlock = 165,
        Astc_6x6_SrgbBlock = 166,
        Astc_8x5_UnormBlock = 167,
        Astc_8x5_SrgbBlock = 168,
        Astc_8x6_UnormBlock = 169,
        Astc_8x6_SrgbBlock = 170,
        Astc_8x8_UnormBlock = 171,
        Astc_8x8_SrgbBlock = 172,
        Astc_10x5_UnormBlock = 173,
        Astc_10x5_SrgbBlock = 174,
        Astc_10x6_UnormBlock = 175,
        Astc_10x6_SrgbBlock = 176,
        Astc_10x8_UnormBlock = 177,
        Astc_10x8_SrgbBlock = 178,
        Astc_10x10_UnormBlock = 179,
        Astc_10x10_SrgbBlock = 180,
        Astc_12x10_UnormBlock = 181,
        Astc_12x10_SrgbBlock = 182,
        Astc_12x12_UnormBlock = 183,
        Astc_12x12_SrgbBlock = 184,
    }

    public enum VkFrontFace {
        CounterClockwise = 0,
        Clockwise = 1,
    }

    public enum VkImageLayout {
        Undefined = 0,
        General = 1,
        ColorAttachmentOptimal = 2,
        DepthStencilAttachmentOptimal = 3,
        DepthStencilReadOnlyOptimal = 4,
        ShaderReadOnlyOptimal = 5,
        TransferSrcOptimal = 6,
        TransferDstOptimal = 7,
        Preinitialized = 8,
        PresentSrcKhr = 1000001002,
    }

    public enum VkImageTiling {
        Optimal = 0,
        Linear = 1,
    }

    public enum VkImageType {
        _1D = 0,
        _2D = 1,
        _3D = 2,
    }

    public enum VkImageViewType {
        _1D = 0,
        _2D = 1,
        _3D = 2,
        Cube = 3,
        _1D_Array = 4,
        _2D_Array = 5,
        CubeArray = 6,
    }

    public enum VkSharingMode {
        Exclusive = 0,
        Concurrent = 1,
    }

    public enum VkIndexType {
        UINT16 = 0,
        UINT32 = 1,
    }

    public enum VkLogicOp {
        Clear = 0,
        And = 1,
        AndReverse = 2,
        Copy = 3,
        AndInverted = 4,
        NoOp = 5,
        Xor = 6,
        Or = 7,
        Nor = 8,
        Equivalent = 9,
        Invert = 10,
        OrReverse = 11,
        CopyInverted = 12,
        OrInverted = 13,
        Nand = 14,
        Set = 15,
    }

    public enum VkPhysicalDeviceType {
        Other = 0,
        IntegratedGpu = 1,
        DiscreteGpu = 2,
        VirtualGpu = 3,
        Cpu = 4,
    }

    public enum VkPipelineBindPoint {
        Graphics = 0,
        Compute = 1,
    }

    public enum VkPrimitiveTopology {
        PointList = 0,
        LineList = 1,
        LineStrip = 2,
        TriangleList = 3,
        TriangleStrip = 4,
        TriangleFan = 5,
        LineListWithAdjacency = 6,
        LineStripWithAdjacency = 7,
        TriangleListWithAdjacency = 8,
        TriangleStripWithAdjacency = 9,
        PatchList = 10,
    }

    public enum VkQueryType {
        Occlusion = 0,
        PipelineStatistics = 1,
        Timestamp = 2,
    }

    public enum VkSubpassContents {
        Inline = 0,
        SecondaryCommandBuffers = 1,
    }

    public enum VkResult {
        Success = 0,
        NotReady = 1,
        Timeout = 2,
        EventSet = 3,
        EventReset = 4,
        Incomplete = 5,
        ErrorOutOfHostMemory = -1,
        ErrorOutOfDeviceMemory = -2,
        ErrorInitializationFailed = -3,
        ErrorDeviceLost = -4,
        ErrorMemoryMapFailed = -5,
        ErrorLayerNotPresent = -6,
        ErrorExtensionNotPresent = -7,
        ErrorFeatureNotPresent = -8,
        ErrorIncompatibleDriver = -9,
        ErrorTooManyObjects = -10,
        ErrorFormatNotSupported = -11,
        ErrorFragmentedPool = -12,
        ErrorSurfaceLostKhr = -1000000000,
        ErrorNativeWindowInUseKhr = -1000000001,
        SuboptimalKhr = 1000001003,
        ErrorOutOfDateKhr = -1000001004,
        ErrorValidationFailedExt = -1000011001,
    }

    public enum VkStencilOp {
        Keep = 0,
        Zero = 1,
        Replace = 2,
        IncrementAndClamp = 3,
        DecrementAndClamp = 4,
        Invert = 5,
        IncrementAndWrap = 6,
        DecrementAndWrap = 7,
    }

    public enum VkStructureType {
        ApplicationInfo = 0,
        InstanceCreateInfo = 1,
        DeviceQueueCreateInfo = 2,
        DeviceCreateInfo = 3,
        SubmitInfo = 4,
        MemoryAllocateInfo = 5,
        MappedMemoryRange = 6,
        BindSparseInfo = 7,
        FenceCreateInfo = 8,
        SemaphoreCreateInfo = 9,
        EventCreateInfo = 10,
        QueryPoolCreateInfo = 11,
        BufferCreateInfo = 12,
        BufferViewCreateInfo = 13,
        ImageCreateInfo = 14,
        ImageViewCreateInfo = 15,
        ShaderModuleCreateInfo = 16,
        PipelineCacheCreateInfo = 17,
        PipelineShaderStageCreateInfo = 18,
        PipelineVertexInputStateCreateInfo = 19,
        PipelineInputAssemblyStateCreateInfo = 20,
        PipelineTessellationStateCreateInfo = 21,
        PipelineViewportStateCreateInfo = 22,
        PipelineRasterizationStateCreateInfo = 23,
        PipelineMultisampleStateCreateInfo = 24,
        PipelineDepthStencilStateCreateInfo = 25,
        PipelineColorBlendStateCreateInfo = 26,
        PipelineDynamicStateCreateInfo = 27,
        GraphicsPipelineCreateInfo = 28,
        ComputePipelineCreateInfo = 29,
        PipelineLayoutCreateInfo = 30,
        SamplerCreateInfo = 31,
        DescriptorSetLayoutCreateInfo = 32,
        DescriptorPoolCreateInfo = 33,
        DescriptorSetAllocateInfo = 34,
        WriteDescriptorSet = 35,
        CopyDescriptorSet = 36,
        FramebufferCreateInfo = 37,
        RenderPassCreateInfo = 38,
        CommandPoolCreateInfo = 39,
        CommandBufferAllocateInfo = 40,
        CommandBufferInheritanceInfo = 41,
        CommandBufferBeginInfo = 42,
        RenderPassBeginInfo = 43,
        BufferMemoryBarrier = 44,
        ImageMemoryBarrier = 45,
        MemoryBarrier = 46,
        LoaderInstanceCreateInfo = 47,
        LoaderDeviceCreateInfo = 48,
        SwapchainCreateInfoKhr = 1000001000,
        PresentInfoKhr = 1000001001,
        DebugReportCallbackCreateInfoExt = 1000011000,
    }

    public enum VkSystemAllocationScope {
        Command = 0,
        Object = 1,
        Cache = 2,
        Device = 3,
        Instance = 4,
    }

    public enum VkInternalAllocationType {
        Executable = 0,
    }

    public enum VkSamplerAddressMode {
        Repeat = 0,
        MirroredRepeat = 1,
        ClampToEdge = 2,
        ClampToBorder = 3,
    }

    public enum VkFilter {
        Nearest = 0,
        Linear = 1,
    }

    public enum VkSamplerMipmapMode {
        Nearest = 0,
        Linear = 1,
    }

    public enum VkVertexInputRate {
        Vertex = 0,
        Instance = 1,
    }

    public enum VkObjectType {
        Unknown = 0,
        Instance = 1,
        PhysicalDevice = 2,
        Device = 3,
        Queue = 4,
        Semaphore = 5,
        CommandBuffer = 6,
        Fence = 7,
        DeviceMemory = 8,
        Buffer = 9,
        Image = 10,
        Event = 11,
        QueryPool = 12,
        BufferView = 13,
        ImageView = 14,
        ShaderModule = 15,
        PipelineCache = 16,
        PipelineLayout = 17,
        RenderPass = 18,
        Pipeline = 19,
        DescriptorSetLayout = 20,
        Sampler = 21,
        DescriptorPool = 22,
        DescriptorSet = 23,
        Framebuffer = 24,
        CommandPool = 25,
        SurfaceKhr = 1000000000,
        SwapchainKhr = 1000001000,
        DebugReportCallbackExt = 1000011000,
    }

    public enum VkColorSpaceKHR {
        SrgbNonlinearKhr = 0,
    }

    public enum VkPresentModeKHR {
        ImmediateKhr = 0,
        MailboxKhr = 1,
        FifoKhr = 2,
        FifoRelaxedKhr = 3,
    }

    public enum VkDebugReportObjectTypeEXT {
        UnknownExt = 0,
        InstanceExt = 1,
        PhysicalDeviceExt = 2,
        DeviceExt = 3,
        QueueExt = 4,
        SemaphoreExt = 5,
        CommandBufferExt = 6,
        FenceExt = 7,
        DeviceMemoryExt = 8,
        BufferExt = 9,
        ImageExt = 10,
        EventExt = 11,
        QueryPoolExt = 12,
        BufferViewExt = 13,
        ImageViewExt = 14,
        ShaderModuleExt = 15,
        PipelineCacheExt = 16,
        PipelineLayoutExt = 17,
        RenderPassExt = 18,
        PipelineExt = 19,
        DescriptorSetLayoutExt = 20,
        SamplerExt = 21,
        DescriptorPoolExt = 22,
        DescriptorSetExt = 23,
        FramebufferExt = 24,
        CommandPoolExt = 25,
        SurfaceKhrExt = 26,
        SwapchainKhrExt = 27,
        DebugReportCallbackExtExt = 28,
        DisplayKhrExt = 29,
        DisplayModeKhrExt = 30,
        ObjectTableNvxExt = 31,
        IndirectCommandsLayoutNvxExt = 32,
    }

    public enum VkValidationCheckEXT {
        AllExt = 0,
        ShadersExt = 1,
    }

}
